/**
 * @license
 * Copyright 2025 Qwen Code
 * SPDX-License-Identifier: Apache-2.0
 */

import { Storage } from '../config/storage.js';
import { persistUsageBeforeTranscriptDeletion } from './usageHistoryService.js';
import { getProjectHash } from '../utils/paths.js';
import path from 'node:path';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import readline from 'node:readline';
import type { Content, Part } from '@google/genai';
import * as jsonl from '../utils/jsonl-utils.js';
import type { HistoryGap } from '../utils/conversation-chain.js';
import { prepareTranscriptRecords } from '../utils/transcript-records.js';
import type {
  ChatRecord,
  FileHistorySnapshotRecordPayload,
  TitleSource,
  UiTelemetryRecordPayload,
  UserPromptRecordPayload,
} from './chatRecordingService.js';
import type { FileHistorySnapshot } from './fileHistoryService.js';
import {
  deserializeSnapshots,
  FILE_HISTORY_DIR,
  serializeSnapshot,
} from './fileHistoryService.js';
import { SessionFileHistoryAccumulator } from './session-file-history-state.js';
import { uiTelemetryService } from '../telemetry/uiTelemetry.js';
import { createDebugLogger } from '../utils/debugLogger.js';
import { readRuntimeStatus } from '../utils/runtimeStatus.js';
import {
  LITE_READ_BUF_SIZE,
  readLastJsonStringFieldSync,
  readSessionTitleInfoFromFileSync,
} from '../utils/sessionStorageUtils.js';
import {
  isSessionArtifactRecord,
  rebuildSessionArtifactSnapshot,
  remapSessionArtifactPayloadForFork,
  selectActiveSideArtifactRecordUuids,
  type RebuiltSessionArtifactSnapshot,
} from './session-artifact-persistence.js';
import { SessionOrganizationService } from './session-organization-service.js';
import {
  SessionTranscriptReader,
  SessionTranscriptTooLargeError,
  type SelectiveSessionRestoreOptions,
  type SessionLiveRestoreProjection,
  type SessionRestoreProjection,
} from './session-transcript-reader.js';
import {
  SessionWriterLease,
  SessionWriterUnavailableError,
  type SessionWriterProcessKind,
} from './session-writer-lease.js';
import {
  parseBranchCheckpointPayload,
  resolveBranchPoints,
} from './branch-points.js';
export {
  buildApiHistoryFromConversation,
  type BuildApiHistoryOptions,
} from './session-api-history.js';
import {
  getResumeTokenCounts,
  type ResumeTokenCounts,
} from './session-resume-token-counts.js';
export {
  getResumePromptTokenCount,
  getResumeTokenCounts,
  type ResumeTokenCounts,
} from './session-resume-token-counts.js';

const debugLogger = createDebugLogger('SESSION');

export class BranchPointInvalidError extends Error {
  constructor(readonly recordId: string) {
    super(`Invalid or inactive branch point: ${recordId}`);
    this.name = 'BranchPointInvalidError';
  }
}

export interface ForkSessionOptions {
  atRecordId?: string;
  title?: string;
  source?: { sourceType: string; sourceId?: string };
}

/**
 * Session item for list display.
 * Contains essential info extracted from the first record of a session file.
 */
export interface SessionListItem {
  /** Unique session identifier */
  sessionId: string;
  /** Working directory at session start */
  cwd: string;
  /** ISO 8601 timestamp when session started */
  startTime: string;
  /** File modification time (used for ordering and pagination) */
  mtime: number;
  /** First user prompt text (truncated for display) */
  prompt: string;
  /** Git branch at session start, if available */
  gitBranch?: string;
  /** Full path to the session file */
  filePath: string;
  /**
   * Number of unique-UUID user/assistant messages, when known. Listing
   * does NOT compute this — counting requires a full readline pass over
   * the JSONL and was the dominant cost of `listSessions` once a project
   * accumulated many sessions. Use {@link SessionService.countSessionMessages}
   * (or compute from the resumed conversation) when the count is needed.
   */
  messageCount?: number;
  /** Custom title set via /rename or auto-generated by the title service, if any */
  customTitle?: string;
  /**
   * Source of {@link customTitle}. `undefined` on legacy records without a
   * source field — consumers should treat `undefined` and `'manual'` the
   * same way for display (full-contrast). UI affordances like dimming are
   * reserved for `'auto'` so users can tell a model guess from a name they
   * chose.
   */
  titleSource?: TitleSource;
  /** Id of the session that spawned this one (via `create_sub_session`), if
   * any. Read from the transcript's `parent_session` record. Absent for a
   * top-level session. */
  parentSessionId?: string;
  /** Immutable creator attribution read from `session_source`. */
  sourceType?: string;
  /** Optional source-specific identifier paired with `sourceType`. */
  sourceId?: string;
  /** True when the item was read from the archive directory. */
  isArchived?: boolean;
}

export type SessionArchiveState = 'active' | 'archived';

export type SessionLocation = SessionArchiveState | 'conflict' | undefined;

/**
 * Pagination options for listing sessions.
 */
export interface ListSessionsOptions {
  /**
   * Cursor for pagination (mtime of the last item from previous page).
   * Items with mtime < cursor will be returned.
   * If undefined, starts from the most recent.
   */
  cursor?: number;
  /**
   * Maximum number of items to return.
   * @default 20
   */
  size?: number;
  /**
   * Which session directory to list.
   * @default 'active'
   */
  archiveState?: SessionArchiveState;
  /** Aborts an in-progress catalog scan. */
  signal?: AbortSignal;
}

/**
 * Result of listing sessions with pagination info.
 */
export interface ListSessionsResult {
  /** Session items for this page */
  items: SessionListItem[];
  /**
   * Cursor for next page (mtime of last item).
   * Undefined if no more items.
   */
  nextCursor?: number;
  /** Whether there are more items after this page */
  hasMore: boolean;
}

/**
 * Aggregate persisted-session counts for a workspace.
 *
 * Built by scanning local JSONL files. This is intentionally separate from
 * {@link listSessions} so paginated list callers are not forced into a full
 * disk walk.
 */
export interface SessionInfoCounts {
  /** Persisted active (non-archived) sessions belonging to this project. */
  active: number;
  /** Persisted archived sessions belonging to this project. */
  archived: number;
  /** `active + archived`. */
  total: number;
  /**
   * True when the scan could not classify every candidate session file, so
   * counts may be lower than the true population.
   */
  truncated: boolean;
}

/**
 * Result of removing multiple sessions.
 */
export interface RemoveSessionsResult {
  removed: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface ArchiveSessionsResult {
  archived: string[];
  alreadyArchived: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface ArchiveSessionsOptions {
  knownLocation?: 'active';
}

export interface UnarchiveSessionsResult {
  unarchived: string[];
  alreadyActive: string[];
  notFound: string[];
  errors: Array<{ sessionId: string; error: Error }>;
}

export interface UnarchiveSessionsOptions {
  knownLocation?: 'archived';
}

export interface SessionServiceOptions {
  onWarning?: (message: string) => void;
  runtimeBaseDir?: string;
}

/**
 * Complete conversation reconstructed from ChatRecords.
 * Used for resuming sessions and API compatibility.
 */
export interface ConversationRecord {
  sessionId: string;
  projectHash: string;
  startTime: string;
  lastUpdated: string;
  /** Messages in chronological order (reconstructed from tree) */
  messages: ChatRecord[];
}

/**
 * Data structure for resuming an existing session.
 */
export interface ResumedSessionData {
  conversation: ConversationRecord;
  filePath: string;
  /** UUID of the last completed message - new messages should use this as parentUuid */
  lastCompletedUuid: string | null;
  /** Deserialized file history snapshots for resume (enables /rewind across sessions) */
  fileHistorySnapshots?: FileHistorySnapshot[];
  /** Persisted session artifact metadata reconstructed from JSONL records. */
  artifactSnapshot?: RebuiltSessionArtifactSnapshot;
  /**
   * Breaks in the persisted parentUuid chain that were detected during
   * reconstruction (an earlier segment of history was physically lost and could
   * not be recovered). Lets the surface render a visible gap divider. Undefined
   * when the chain was intact.
   */
  historyGaps?: HistoryGap[];
}

/**
 * Maximum number of files to process when listing sessions.
 * This is a safety limit to prevent performance issues with very large chat directories.
 */
const MAX_FILES_TO_PROCESS = 10000;
const SESSION_LIST_CANCEL_YIELD_INTERVAL = 128;

/**
 * Maximum character length for a session custom title.
 * Shared across CLI, WebUI, VSCode, and ACP.
 */
export const SESSION_TITLE_MAX_LENGTH = 200;

/**
 * Pattern for validating session file names.
 * Session files are named as `${sessionId}.jsonl` where sessionId is a UUID-like identifier
 * (32-36 hex characters, optionally with hyphens).
 */
const SESSION_FILE_PATTERN = /^[0-9a-fA-F-]{32,36}\.jsonl$/;
/** Maximum number of lines to scan when looking for the first prompt text. */
const MAX_PROMPT_SCAN_LINES = 10;
/**
 * Maximum bytes to read from head/tail of a session file.
 * Used by readLastRecordUuid which still does its own tail read.
 */
const TAIL_READ_SIZE = 64 * 1024;

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.promises.access(filePath);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false;
    throw error;
  }
}

async function fsyncPath(filePath: string): Promise<void> {
  const handle = await fs.promises.open(filePath, 'r');
  try {
    await handle.sync();
  } finally {
    await handle.close();
  }
}

async function fsyncDirectoryBestEffort(directory: string): Promise<void> {
  try {
    await fsyncPath(directory);
  } catch (error) {
    if (process.platform !== 'win32') throw error;
  }
}

function validatedBackupPath(directory: string, name: string): string {
  if (name.length === 0 || path.basename(name) !== name) {
    throw new Error(`Invalid file-history backup name: ${name}`);
  }
  const resolvedDirectory = path.resolve(directory);
  const resolved = path.resolve(directory, name);
  if (path.dirname(resolved) !== resolvedDirectory) {
    throw new Error(`File-history backup escapes its directory: ${name}`);
  }
  return resolved;
}

async function copyFileHistoryBackupsToStaging(
  sourceSessionId: string,
  targetDirectory: string,
  backupNames: ReadonlySet<string>,
  onMissing: (name: string) => void,
): Promise<Set<string>> {
  const copiedNames = new Set<string>();
  if (backupNames.size === 0) return copiedNames;
  const sourceDir = path.join(
    Storage.getGlobalQwenDir(),
    FILE_HISTORY_DIR,
    sourceSessionId,
  );
  const copyBuffer = Buffer.alloc(64 * 1024);
  let stagingCreated = false;
  const ensureStaging = async () => {
    if (stagingCreated) return;
    await fs.promises.mkdir(targetDirectory, {
      recursive: false,
      mode: 0o700,
    });
    stagingCreated = true;
  };
  for (const name of backupNames) {
    const source = validatedBackupPath(sourceDir, name);
    const target = validatedBackupPath(targetDirectory, name);
    let sourceHandle: fs.promises.FileHandle;
    try {
      sourceHandle = await fs.promises.open(
        source,
        fs.constants.O_RDONLY |
          (process.platform === 'win32' ? 0 : fs.constants.O_NOFOLLOW),
      );
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      if (code === 'ENOENT' || code === 'ELOOP') {
        onMissing(name);
        continue;
      }
      throw error;
    }
    try {
      const sourceStat = await sourceHandle.stat();
      let pathStat: fs.Stats;
      try {
        pathStat = await fs.promises.lstat(source);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
        onMissing(name);
        continue;
      }
      if (
        !sourceStat.isFile() ||
        !pathStat.isFile() ||
        sourceStat.dev !== pathStat.dev ||
        sourceStat.ino !== pathStat.ino
      ) {
        onMissing(name);
        continue;
      }

      await ensureStaging();
      const targetHandle = await fs.promises.open(target, 'wx', 0o600);
      try {
        let sourceOffset = 0;
        while (true) {
          const { bytesRead } = await sourceHandle.read(
            copyBuffer,
            0,
            copyBuffer.length,
            sourceOffset,
          );
          if (bytesRead === 0) break;
          let written = 0;
          while (written < bytesRead) {
            const result = await targetHandle.write(
              copyBuffer,
              written,
              bytesRead - written,
              null,
            );
            if (result.bytesWritten === 0) {
              throw new Error(`Failed to copy file-history backup: ${name}`);
            }
            written += result.bytesWritten;
          }
          sourceOffset += bytesRead;
        }
        await targetHandle.chmod(sourceStat.mode & 0o7777);
        await targetHandle.sync();
      } finally {
        await targetHandle.close();
      }
      copiedNames.add(name);
    } finally {
      await sourceHandle.close();
    }
  }
  return copiedNames;
}

/**
 * Service for managing chat sessions.
 *
 * This service handles:
 * - Listing sessions with pagination (ordered by mtime)
 * - Loading full session data for resumption
 * - Removing sessions
 *
 * Sessions are stored as JSONL files, one per session.
 * File location: ~/.qwen/tmp/<project_id>/chats/
 */
export class SessionService {
  private readonly storage: Storage;
  private readonly projectHash: string;
  private readonly projectRoot: string;
  private readonly onWarning: ((message: string) => void) | undefined;
  private readonly transcriptReader: SessionTranscriptReader;

  constructor(cwd: string, options: SessionServiceOptions = {}) {
    this.storage = new Storage(cwd, options.runtimeBaseDir);
    this.projectRoot = cwd;
    this.projectHash = getProjectHash(cwd);
    this.onWarning = options.onWarning;
    this.transcriptReader = new SessionTranscriptReader(
      cwd,
      undefined,
      options.runtimeBaseDir,
    );
  }

  /** The workspace root this service is bound to (the cwd it was constructed
   * with). Lets callers that already hold a service — e.g. the session
   * archive/delete choke points — reach per-project state such as the durable
   * scheduled-tasks file without re-plumbing the workspace path. */
  getProjectRoot(): string {
    return this.projectRoot;
  }

  async acquireSessionWriterLease(
    sessionId: string,
    options: {
      processKind: SessionWriterProcessKind;
      qwenVersion?: string | null;
      reclaimPolicy: 'local' | 'never';
    },
  ): Promise<SessionWriterLease> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      throw new SessionWriterUnavailableError();
    }
    return SessionWriterLease.acquire({
      runtimeBaseDir: this.storage.getRuntimeBaseDir(),
      sessionId,
      transcriptPath: this.getSessionFilePath(sessionId, 'active'),
      ...options,
    });
  }

  private warn(message: string): void {
    debugLogger.warn(message);
    this.onWarning?.(message);
  }

  private getChatsDir(): string {
    return path.join(this.storage.getProjectDir(), 'chats');
  }

  private getArchiveChatsDir(): string {
    return path.join(this.getChatsDir(), 'archive');
  }

  private getChatsDirForState(state: SessionArchiveState): string {
    return state === 'archived'
      ? this.getArchiveChatsDir()
      : this.getChatsDir();
  }

  private getSessionFilePath(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return path.join(this.getChatsDirForState(state), `${sessionId}.jsonl`);
  }

  private getWorktreeSessionPathForState(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return path.join(
      this.getChatsDirForState(state),
      `${sessionId}.worktree.json`,
    );
  }

  private async sessionBelongsToCurrentProject(
    sessionId: string,
    recordCwd: string,
    signal?: AbortSignal,
  ): Promise<boolean> {
    signal?.throwIfAborted();
    if (getProjectHash(recordCwd) === this.projectHash) {
      return true;
    }

    // Worktree sessions record cwd as the worktree path
    // (<repoRoot>/.qwen/worktrees/<slug>), which has a different project
    // hash. Infer the repo root from the path and check its hash. This
    // is durable — it doesn't depend on the sidecar file, which is
    // transient and cleared when the worktree is removed. Pure string
    // ops, so check before the file-read runtime status below.
    // Use lastIndexOf to handle nested worktrees: for
    // /repo/.qwen/worktrees/parent/.qwen/worktrees/child, the innermost
    // marker gives repoRoot = /repo/.qwen/worktrees/parent (the workspace).
    const worktreesMarker = `${path.sep}.qwen${path.sep}worktrees${path.sep}`;
    const markerIdx = recordCwd.lastIndexOf(worktreesMarker);
    if (markerIdx > 0) {
      const repoRoot = recordCwd.substring(0, markerIdx);
      if (getProjectHash(repoRoot) === this.projectHash) {
        return true;
      }
    }

    const runtimeStatusPath = this.storage.getRuntimeStatusPath(sessionId);
    const status = signal
      ? await readRuntimeStatus(runtimeStatusPath, { signal })
      : await readRuntimeStatus(runtimeStatusPath);
    signal?.throwIfAborted();
    return (
      status?.sessionId === sessionId &&
      getProjectHash(status.workDir) === this.projectHash
    );
  }

  /**
   * Returns the absolute path to the sidecar JSON file that stores
   * worktree session state for the given session id. The file may not
   * exist yet — consumers must handle ENOENT as "no active worktree".
   */
  getWorktreeSessionPath(sessionId: string): string {
    return this.getWorktreeSessionPathForState(sessionId, 'active');
  }

  getWorktreeSessionPathForArchiveState(
    sessionId: string,
    state: SessionArchiveState,
  ): string {
    return this.getWorktreeSessionPathForState(sessionId, state);
  }

  private async readProjectSessionHead(
    sessionId: string,
    filePath: string,
  ): Promise<ChatRecord | undefined> {
    try {
      const records = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (records.length === 0) {
        return undefined;
      }
      const firstRecord = records[0];
      if (
        !(await this.sessionBelongsToCurrentProject(sessionId, firstRecord.cwd))
      ) {
        return undefined;
      }
      return firstRecord;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return undefined;
      }
      this.warn(`readProjectSessionHead: failed to read ${filePath}: ${error}`);
      throw error;
    }
  }

  /**
   * Reads the persisted `parentSessionId` for a single session (active or
   * archived), or undefined when it has no parent. Used to re-seed a live entry
   * on restore/resume so a restored sub-session's status still reports its
   * lineage after a daemon restart. Best-effort: a read failure returns
   * undefined rather than throwing — a missing link must never fail a restore.
   */
  async readParentSessionId(sessionId: string): Promise<string | undefined> {
    return (await this.readCreationMetadata(sessionId)).parentSessionId;
  }

  /** Reads immutable creation metadata for an active or archived session. */
  async readCreationMetadata(sessionId: string): Promise<{
    parentSessionId?: string;
    sourceType?: string;
    sourceId?: string;
  }> {
    for (const state of ['active', 'archived'] as const) {
      const filePath = this.getSessionFilePath(sessionId, state);
      try {
        const records = await jsonl.readLines<ChatRecord>(
          filePath,
          MAX_PROMPT_SCAN_LINES,
        );
        if (records.length === 0) continue;
        if (
          !(await this.sessionBelongsToCurrentProject(
            records[0].sessionId,
            records[0].cwd,
          ))
        ) {
          continue;
        }
        return this.extractCreationMetadataFromRecords(records);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
        this.warn(
          `readCreationMetadata: failed to read ${sessionId}: ${error}`,
        );
      }
    }
    return {};
  }

  async getSessionLocation(sessionId: string): Promise<SessionLocation> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return undefined;
    }

    const [active, archived] = await Promise.all([
      this.readProjectSessionHead(
        sessionId,
        this.getSessionFilePath(sessionId, 'active'),
      ),
      this.readProjectSessionHead(
        sessionId,
        this.getSessionFilePath(sessionId, 'archived'),
      ),
    ]);

    if (active && archived) return 'conflict';
    if (active) return 'active';
    if (archived) return 'archived';
    return undefined;
  }

  /**
   * Finds a persisted session whose UUID filename differs only by case.
   * Legacy CLI sessions may have been written with `uuidgen`'s uppercase
   * spelling, while daemon-facing caller IDs are canonicalized to lowercase.
   */
  async findSessionIdIgnoringCase(
    sessionId: string,
  ): Promise<string | undefined> {
    const expectedFileName = `${sessionId}.jsonl`.toLowerCase();
    for (const state of ['active', 'archived'] as const) {
      let fileNames: string[];
      try {
        fileNames = fs.readdirSync(this.getChatsDirForState(state));
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
        throw error;
      }
      for (const fileName of fileNames) {
        if (fileName.toLowerCase() !== expectedFileName) continue;
        const candidateSessionId = fileName.slice(0, -'.jsonl'.length);
        const location = await this.getSessionLocation(candidateSessionId);
        if (location !== undefined) return candidateSessionId;
      }
    }
    return undefined;
  }

  private removeFileIfExists(filePath: string): void {
    try {
      fs.unlinkSync(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }
  }

  private removeWorktreeSidecars(sessionId: string): void {
    for (const state of ['active', 'archived'] as const) {
      const sidecar = this.getWorktreeSessionPathForState(sessionId, state);
      if (fs.existsSync(sidecar)) {
        this.removeFileIfExists(sidecar);
      }
    }
  }

  private removeFileHistoryBackups(sessionId: string): void {
    fs.rmSync(
      path.join(Storage.getGlobalQwenDir(), FILE_HISTORY_DIR, sessionId),
      { recursive: true, force: true },
    );
  }

  private async removeSessionOrganization(sessionId: string): Promise<void> {
    try {
      await new SessionOrganizationService(this.projectRoot, (message) => {
        this.warn(message);
      }).removeSession(sessionId);
    } catch (error) {
      this.warn(
        `removeSession: failed to clear session organization for ${sessionId}: ${error}`,
      );
    }
  }

  private async removeSessionOrganizations(
    sessionIds: string[],
  ): Promise<void> {
    if (sessionIds.length === 0) return;
    try {
      await new SessionOrganizationService(this.projectRoot, (message) => {
        this.warn(message);
      }).removeSessions(sessionIds);
    } catch (error) {
      this.warn(
        `removeSessions: failed to clear session organization for ${sessionIds.join(
          ', ',
        )}: ${error}`,
      );
    }
  }

  private moveOptionalFile(sourcePath: string, targetPath: string): boolean {
    if (!fs.existsSync(sourcePath)) {
      return false;
    }
    if (fs.existsSync(targetPath)) {
      throw new Error('Archive sidecar conflict: destination already exists');
    }
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.renameSync(sourcePath, targetPath);
    return true;
  }

  private sessionFileMoveError(
    action: 'archive' | 'unarchive',
    error: unknown,
  ): Error {
    const code = (error as NodeJS.ErrnoException).code ?? 'unknown error';
    return new Error(`Failed to ${action} session file: ${code}`);
  }

  /**
   * Reads the session title from a JSONL file.
   *
   * Delegates to {@link readLastJsonStringFieldSync}, which scans the tail
   * window first (fast path; almost always hits because finalize() re-appends
   * the title on every lifecycle event) and falls back to a bounded head
   * window when the tail has no match. The `custom_title` line-marker guards
   * against false matches from user content that happens to include a
   * `customTitle` field.
   */
  private readSessionTitleFromFile(
    filePath: string,
    tailBuffer?: Buffer,
  ): string | undefined {
    // Match only on actual custom_title system records. `'custom_title'` as
    // a loose substring can land on a user message that happens to contain
    // the literal "custom_title" (code review of this very file, etc.);
    // requiring the full `"subtype":"custom_title"` pattern guarantees the
    // match is on a system record written by {@link writeLineSync}, which
    // JSON.stringifies records in a predictable compact form.
    return readLastJsonStringFieldSync(
      filePath,
      'customTitle',
      '"subtype":"custom_title"',
      tailBuffer,
    );
  }

  /**
   * Reads both the custom title and its source from a session file in a
   * single pass — the helper extracts both fields from the same matching
   * `custom_title` line, so the pair is always consistent (never one field
   * from an old record and another from a new one).
   *
   * `titleSource` is absent on legacy records written before the field was
   * introduced — callers treat `undefined` as equivalent to `'manual'` so a
   * user's pre-upgrade rename is never displayed as if it were auto-generated.
   */
  private readSessionTitleInfoFromFile(
    filePath: string,
    tailBuffer?: Buffer,
  ): {
    title?: string;
    source?: TitleSource;
  } {
    return readSessionTitleInfoFromFileSync(filePath, tailBuffer);
  }

  /**
   * Extracts the `parent_session` record's `parentSessionId` from records
   * ALREADY read for the listing (the first {@link MAX_PROMPT_SCAN_LINES}), or
   * undefined when the session has no parent. The record is written once right
   * after the sub-session is created — before any prompt — so it is reliably
   * within that window. No extra file open, unlike the title (which re-anchors
   * at EOF and needs its own tail-then-head scan).
   */
  private extractCreationMetadataFromRecords(records: ChatRecord[]): {
    parentSessionId?: string;
    sourceType?: string;
    sourceId?: string;
  } {
    let parentSessionId: string | undefined;
    let sourceType: string | undefined;
    let sourceId: string | undefined;
    for (const record of records) {
      if (record.type === 'system' && record.subtype === 'parent_session') {
        const payload = record.systemPayload as
          | { parentSessionId?: unknown }
          | undefined;
        if (
          parentSessionId === undefined &&
          typeof payload?.parentSessionId === 'string'
        ) {
          parentSessionId = payload.parentSessionId;
        }
      }
      if (record.type === 'system' && record.subtype === 'session_source') {
        const payload = record.systemPayload as
          | { sourceType?: unknown; sourceId?: unknown }
          | undefined;
        if (
          sourceType === undefined &&
          typeof payload?.sourceType === 'string'
        ) {
          sourceType = payload.sourceType;
          sourceId =
            typeof payload.sourceId === 'string' ? payload.sourceId : undefined;
        }
      }
    }
    return {
      ...(parentSessionId ? { parentSessionId } : {}),
      ...(sourceType ? { sourceType } : {}),
      ...(sourceId !== undefined ? { sourceId } : {}),
    };
  }

  /**
   * Public accessor: returns both the current custom title and its source
   * for a given session. Used by `ChatRecordingService` on resume to
   * preserve the persisted `titleSource` rather than defaulting to manual.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitleInfo(sessionId: string): {
    title?: string;
    source?: TitleSource;
  } {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return {};
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);
    return this.readSessionTitleInfoFromFile(filePath);
  }

  /**
   * Reads the UUID of the last record in a session JSONL file.
   * Uses a tail-read strategy for efficiency.
   *
   * Each physical line is routed through `jsonl.parseLineTolerant` so a
   * `}{`-glued tail line (#3606 corruption shape) still yields its records
   * instead of being silently skipped — otherwise `renameSession` would set
   * `custom_title.parentUuid` to a stale uuid and `reconstructHistory` would
   * truncate the chain on resume.
   */
  private readLastRecordUuid(filePath: string): string | null {
    try {
      const stats = fs.statSync(filePath);
      const fileSize = stats.size;
      const readStart = Math.max(0, fileSize - TAIL_READ_SIZE);
      const readLength = Math.min(fileSize, TAIL_READ_SIZE);

      const fd = fs.openSync(filePath, 'r');
      let buffer: Buffer;
      let firstSegmentIsPartial = false;
      try {
        buffer = Buffer.alloc(readLength);
        fs.readSync(fd, buffer, 0, readLength, readStart);

        // The first split segment is partial only when the tail window
        // truly starts in the middle of a JSONL record. If the byte right
        // before `readStart` is `\n`, the window started on a record
        // boundary and the first segment is a complete line — the
        // 64-KiB-aligned case where `prev\n<exactly-64KiB-record>\n`
        // would otherwise drop the only readable record. Peek that byte
        // before deciding to shift.
        if (readStart > 0) {
          const peek = Buffer.alloc(1);
          fs.readSync(fd, peek, 0, 1, readStart - 1);
          firstSegmentIsPartial = peek[0] !== 0x0a; // 0x0a = '\n'
        }
      } finally {
        fs.closeSync(fd);
      }

      const tail = buffer.toString('utf-8');
      const lines = tail.split('\n');

      // Discard the first segment ONLY when it's a true partial fragment.
      // Running tolerant recovery on a partial would surface a balanced
      // inner `{ "uuid": ... }` object from inside the record's payload as
      // if it were a top-level uuid — `renameSession` would then anchor
      // `custom_title.parentUuid` at payload data and break the parent
      // chain. Complete physical lines (including a boundary-aligned
      // first segment) are safe to recover.
      if (firstSegmentIsPartial) {
        lines.shift();
      }

      // Walk physical lines bottom-up; on each line walk recovered records
      // bottom-up too, so a `}{`-glued tail returns the *latest* record.
      for (let i = lines.length - 1; i >= 0; i--) {
        const trimmed = lines[i].trim();
        if (!trimmed) continue;
        const records = jsonl.parseLineTolerant<ChatRecord>(trimmed, filePath);
        for (let j = records.length - 1; j >= 0; j--) {
          const record = records[j];
          if (record.uuid) {
            return record.uuid;
          }
        }
      }

      return null;
    } catch {
      return null;
    }
  }

  /**
   * Extracts the first user prompt text from a Content object.
   */
  private extractPromptText(message: Content | undefined): string {
    if (!message?.parts) return '';

    for (const part of message.parts as Part[]) {
      if ('text' in part) {
        const textPart = part as { text: string };
        const text = textPart.text;
        return this.truncatePromptForDisplay(text);
      }
    }
    return '';
  }

  /**
   * Finds the first available prompt text by scanning the first N records,
   * preferring user messages. Returns an empty string if none found.
   */
  private extractFirstPromptFromRecords(records: ChatRecord[]): string {
    for (const record of records) {
      if (record.type !== 'user' || record.subtype !== undefined) continue;
      const payload = record.systemPayload as
        | UserPromptRecordPayload
        | undefined;
      if (payload?.displayText !== undefined) {
        const displayText = payload.displayText;
        if (displayText) {
          return this.truncatePromptForDisplay(displayText);
        }
        continue;
      }
      const prompt = this.extractPromptText(record.message);
      if (prompt) {
        return prompt;
      }
    }
    return '';
  }

  private truncatePromptForDisplay(text: string): string {
    const codePoints: string[] = [];
    for (const codePoint of text) {
      if (codePoints.length === 200) {
        return `${codePoints.join('')}...`;
      }
      codePoints.push(codePoint);
    }
    return text;
  }

  /**
   * Counts unique user/assistant message UUIDs in a session file by
   * streaming the JSONL line-by-line. Each physical line is routed
   * through `jsonl.parseLineTolerant` so a `}{`-glued line (#3606
   * corruption shape) still contributes both records, instead of being
   * silently dropped.
   *
   * Project-scoped: returns 0 if the file's first record belongs to a
   * different project. Sibling public methods (deleteSession,
   * renameSession, loadSession) apply the same first-record cwd check;
   * mirroring it here keeps lazy-count callers from accidentally
   * counting a session that lives in the shared chats directory but
   * belongs to another project.
   *
   * This is intentionally NOT called from {@link listSessions} or
   * {@link findSessionsByTitle} — it would be O(total bytes on disk) per
   * picker open, dominating wall time once a project accumulates dozens
   * of multi-MB sessions. Call this lazily, only when a specific
   * session's message count is about to be displayed (e.g., from a
   * preview panel) or computed from a resumed conversation.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async countSessionMessages(sessionId: string): Promise<number> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return 0;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);

    try {
      const firstRecords = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (firstRecords.length === 0) return 0;
      if (
        !(await this.sessionBelongsToCurrentProject(
          sessionId,
          firstRecords[0].cwd,
        ))
      ) {
        return 0;
      }
    } catch {
      return 0;
    }

    return this.countSessionMessagesFromPath(filePath);
  }

  private async countSessionMessagesFromPath(
    filePath: string,
  ): Promise<number> {
    const uniqueUuids = new Set<string>();
    try {
      const fileStream = fs.createReadStream(filePath);
      const rl = readline.createInterface({
        input: fileStream,
        crlfDelay: Infinity,
      });

      for await (const line of rl) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        for (const record of jsonl.parseLineTolerant<ChatRecord>(
          trimmed,
          filePath,
        )) {
          if (record.type === 'user' || record.type === 'assistant') {
            uniqueUuids.add(record.uuid);
          }
        }
      }

      return uniqueUuids.size;
    } catch {
      return 0;
    }
  }

  /**
   * Lists sessions for the current project with pagination.
   *
   * Sessions are ordered by file modification time (most recent first).
   * Uses cursor-based pagination with mtime as the cursor.
   *
   * Only reads the first line of each JSONL file for efficiency.
   * Files are filtered by UUID pattern first, then by project hash.
   *
   * @param options Pagination options
   * @returns Paginated list of sessions
   */
  async listSessions(
    options: ListSessionsOptions = {},
  ): Promise<ListSessionsResult> {
    const { cursor, size = 20, archiveState = 'active', signal } = options;
    const chatsDir = this.getChatsDirForState(archiveState);
    const isArchived = archiveState === 'archived';
    signal?.throwIfAborted();

    // Get all valid session files (matching UUID pattern) with their stats
    let files: Array<{ name: string; mtime: number }> = [];
    try {
      const fileNames = fs.readdirSync(chatsDir);
      signal?.throwIfAborted();
      for (const [index, name] of fileNames.entries()) {
        if (SESSION_FILE_PATTERN.test(name)) {
          const filePath = path.join(chatsDir, name);
          try {
            const stats = fs.statSync(filePath);
            files.push({ name, mtime: stats.mtimeMs });
          } catch {
            // Skip files we can't stat
          }
        }
        if (signal && (index + 1) % SESSION_LIST_CANCEL_YIELD_INTERVAL === 0) {
          signal.throwIfAborted();
          await new Promise<void>((resolve) => setImmediate(resolve));
          signal.throwIfAborted();
        }
      }
    } catch (error) {
      signal?.throwIfAborted();
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return { items: [], hasMore: false };
      }
      throw error;
    }
    signal?.throwIfAborted();

    // Sort by mtime descending (most recent first)
    files.sort((a, b) => b.mtime - a.mtime);
    signal?.throwIfAborted();

    // Apply cursor filter (items with mtime < cursor)
    if (cursor !== undefined) {
      files = files.filter((f) => f.mtime < cursor);
    }

    // Iterate through files until we have enough matching ones.
    // Different projects may share the same chats directory due to path sanitization,
    // so we need to filter by project hash and continue until we have enough items.
    const items: SessionListItem[] = [];
    let filesProcessed = 0;
    let lastProcessedMtime: number | undefined;
    let hasMoreFiles = false;

    // Pre-allocate the tail-read buffer once and pass it to every
    // per-file metadata read. Without pooling, each session in the
    // page allocs+GCs a fresh 64KB Buffer; for a typical page of 20
    // that's ~1.3MB churn per /resume open. The helper reuses this
    // same scratch buffer for its bounded tail and head-window reads.
    const tailBuffer = Buffer.alloc(LITE_READ_BUF_SIZE);

    for (const file of files) {
      signal?.throwIfAborted();
      // Safety limit to prevent performance issues
      if (filesProcessed >= MAX_FILES_TO_PROCESS) {
        hasMoreFiles = true;
        break;
      }

      // Stop if we have enough items
      if (items.length >= size) {
        hasMoreFiles = true;
        break;
      }

      filesProcessed++;
      lastProcessedMtime = file.mtime;

      const filePath = path.join(chatsDir, file.name);
      const records = signal
        ? await jsonl.readLines<ChatRecord>(filePath, MAX_PROMPT_SCAN_LINES, {
            signal,
          })
        : await jsonl.readLines<ChatRecord>(filePath, MAX_PROMPT_SCAN_LINES);
      signal?.throwIfAborted();

      if (records.length === 0) continue;
      const firstRecord = records[0];

      if (
        !(await this.sessionBelongsToCurrentProject(
          firstRecord.sessionId,
          firstRecord.cwd,
          signal,
        ))
      ) {
        continue;
      }

      const prompt = this.extractFirstPromptFromRecords(records);

      signal?.throwIfAborted();
      const titleInfo = this.readSessionTitleInfoFromFile(filePath, tailBuffer);
      signal?.throwIfAborted();
      const source = this.extractCreationMetadataFromRecords(records);
      items.push({
        sessionId: firstRecord.sessionId,
        cwd: firstRecord.cwd,
        startTime: firstRecord.timestamp,
        mtime: file.mtime,
        prompt,
        gitBranch: firstRecord.gitBranch,
        filePath,
        // messageCount intentionally omitted — see SessionListItem
        // and `countSessionMessages` for the rationale.
        customTitle: titleInfo.title,
        titleSource: titleInfo.source,
        ...(source.parentSessionId
          ? { parentSessionId: source.parentSessionId }
          : {}),
        ...(source.sourceType ? { sourceType: source.sourceType } : {}),
        ...(source.sourceId !== undefined ? { sourceId: source.sourceId } : {}),
        isArchived,
      });
    }
    signal?.throwIfAborted();

    // Determine next cursor (mtime of last processed file)
    // Only set if there are more files to process
    const nextCursor =
      hasMoreFiles && lastProcessedMtime !== undefined
        ? lastProcessedMtime
        : undefined;

    return {
      items,
      nextCursor,
      hasMore: hasMoreFiles,
    };
  }

  /**
   * Counts persisted sessions for this project by scanning the active and
   * archived chats directories.
   *
   * Same disk-walk shape as {@link findSessionTitlesByPrefix} /
   * {@link findSessionsByTitle}: `readdir` the chats dir, cap at the
   * file-processing safety limit, then read only the first JSONL record for
   * project membership. Title/prompt/message hydration is skipped entirely.
   *
   * Still an O(n) disk walk — callers (and HTTP clients of
   * `GET .../session-info`) must not poll this in a tight loop.
   */
  async getSessionInfoCounts(): Promise<SessionInfoCounts> {
    const [active, archived] = await Promise.all([
      this.countSessionsInState('active'),
      this.countSessionsInState('archived'),
    ]);
    return {
      active: active.count,
      archived: archived.count,
      total: active.count + archived.count,
      truncated: active.truncated || archived.truncated,
    };
  }

  private async countSessionsInState(
    archiveState: SessionArchiveState,
  ): Promise<{ count: number; truncated: boolean }> {
    const chatsDir = this.getChatsDirForState(archiveState);
    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return { count: 0, truncated: false };
      }
      throw error;
    }

    let count = 0;
    let filesProcessed = 0;
    let truncated = false;

    for (const name of fileNames) {
      if (!SESSION_FILE_PATTERN.test(name)) continue;
      if (filesProcessed >= MAX_FILES_TO_PROCESS) {
        truncated = true;
        break;
      }
      filesProcessed++;

      const filePath = path.join(chatsDir, name);
      // Project filter only — same first-record membership check as
      // findSessionTitlesByPrefix, without the title tail-read (every file
      // is a candidate when counting).
      try {
        const records = await jsonl.readLines<ChatRecord>(filePath, 1);
        if (records.length === 0) {
          truncated = true;
          continue;
        }
        const firstRecord = records[0]!;
        if (
          !(await this.sessionBelongsToCurrentProject(
            firstRecord.sessionId,
            firstRecord.cwd,
          ))
        ) {
          continue;
        }
        count++;
      } catch {
        truncated = true;
        continue;
      }
    }

    return { count, truncated };
  }

  /**
   * Reads all records from a session file.
   */
  private async readAllRecords(filePath: string): Promise<ChatRecord[]> {
    try {
      return await jsonl.read<ChatRecord>(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        debugLogger.error('Error reading session file:', error);
      }
      return [];
    }
  }

  /**
   * Reconstructs a linear conversation from tree-structured records.
   *
   * Delegates validation, parentUuid walking, and fragment aggregation to the
   * shared transcript record preparation module. With
   * `detectGaps`, a walk that stops on a physically-missing parent records the
   * break in the returned `gaps` (see {@link HistoryGap}) so the surface can
   * mark it — the earlier records are NOT reconstructed (reconnecting them
   * could resurrect turns the user rewound away). Without `detectGaps` the
   * result is identical to the historical walk.
   */
  private reconstructHistory(
    records: ChatRecord[],
    opts?: { leafUuid?: string; detectGaps?: boolean },
  ): { messages: ChatRecord[]; gaps: HistoryGap[] } {
    if (records.length === 0) return { messages: [], gaps: [] };
    const prepared = prepareTranscriptRecords(records, {
      ...(opts?.leafUuid !== undefined ? { leafUuid: opts.leafUuid } : {}),
    });
    return {
      messages: prepared.records.map((record) => record as ChatRecord),
      gaps: opts?.detectGaps ? [...prepared.gaps] : [],
    };
  }

  /**
   * Loads a session by its session ID.
   * Reconstructs the full conversation from tree-structured records.
   *
   * @param sessionId The session ID to load
   * @returns Session data for resumption, or undefined if not found
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async loadSession(
    sessionId: string,
  ): Promise<ResumedSessionData | undefined> {
    return this.loadSessionFromState(sessionId, 'active');
  }

  async readRestoreProjection(
    sessionId: string,
    options: SelectiveSessionRestoreOptions,
  ): Promise<SessionRestoreProjection | undefined> {
    return this.transcriptReader.readRestoreProjection(sessionId, options, {
      validateFirstRecord: (record) =>
        this.sessionBelongsToCurrentProject(record.sessionId, record.cwd),
    });
  }

  async readLiveRestoreProjection(
    sessionId: string,
    options: SelectiveSessionRestoreOptions,
  ): Promise<SessionLiveRestoreProjection | undefined> {
    return this.transcriptReader.readLiveRestoreProjection(sessionId, options, {
      validateFirstRecord: (record) =>
        this.sessionBelongsToCurrentProject(record.sessionId, record.cwd),
    });
  }

  /**
   * Reads an archived session without changing its archive state.
   * Daemon load/resume paths must continue to use {@link loadSession}.
   */
  async loadArchivedSession(
    sessionId: string,
    options: { maxBytes: number },
  ): Promise<ResumedSessionData | undefined> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return undefined;
    }
    const filePath = this.getSessionFilePath(sessionId, 'archived');
    let stats: fs.Stats;
    try {
      stats = fs.statSync(filePath);
      if (stats.size > options.maxBytes) {
        throw new SessionTranscriptTooLargeError(
          sessionId,
          stats.size,
          options.maxBytes,
        );
      }
    } catch (error) {
      if (error instanceof SessionTranscriptTooLargeError) {
        throw error;
      }
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
      return undefined;
    }
    return this.loadSessionFromState(sessionId, 'archived', stats);
  }

  private async loadSessionFromState(
    sessionId: string,
    state: SessionArchiveState,
    stats?: fs.Stats,
  ): Promise<ResumedSessionData | undefined> {
    const filePath = this.getSessionFilePath(sessionId, state);

    const records = await this.readAllRecords(filePath);
    if (records.length === 0) {
      return;
    }

    const firstRecord = records[0];
    if (
      !(await this.sessionBelongsToCurrentProject(
        firstRecord.sessionId,
        firstRecord.cwd,
      ))
    ) {
      return;
    }

    // Reconstruct linear history
    const { messages, gaps } = this.reconstructHistory(records, {
      detectGaps: true,
    });
    if (messages.length === 0) {
      return;
    }

    if (gaps.length > 0) {
      debugLogger.warn(
        `loadSession: detected ${gaps.length} unrecoverable history gap(s) ` +
          `for session ${sessionId}: ` +
          gaps
            .map(
              (g) =>
                `child=${g.childUuid} missingParent=${g.missingParentUuid}`,
            )
            .join('; '),
      );
    }

    const lastMessage = messages[messages.length - 1];
    stats ??= await fs.promises.stat(filePath);

    const conversation: ConversationRecord = {
      sessionId: firstRecord.sessionId,
      projectHash: this.projectHash,
      startTime: firstRecord.timestamp,
      lastUpdated: new Date(stats.mtimeMs).toISOString(),
      messages,
    };

    // Extract file history snapshots for /rewind across resume
    const fileHistoryAccumulator = new SessionFileHistoryAccumulator();
    for (const msg of messages) {
      try {
        fileHistoryAccumulator.add(msg);
      } catch (e) {
        debugLogger.warn(
          `loadSession: skipping malformed file_history_snapshot: ${e}`,
        );
      }
    }
    const fileHistorySnapshots = fileHistoryAccumulator.finish();
    const activeBranchRecords = includeActiveSideArtifactRecords(
      records,
      messages,
    );
    const artifactSnapshot = rebuildSessionArtifactSnapshot(
      activeBranchRecords,
      firstRecord.sessionId,
    );

    return {
      conversation,
      filePath,
      lastCompletedUuid: lastMessage.uuid,
      fileHistorySnapshots,
      ...(artifactSnapshot ? { artifactSnapshot } : {}),
      historyGaps: gaps.length > 0 ? gaps : undefined,
    };
  }

  /**
   * Removes a session by its session ID.
   *
   * @param sessionId The session ID to remove
   * @returns true if removed, false if not found
   */
  async removeSession(sessionId: string): Promise<boolean> {
    const removed = await this.removeSessionFiles(sessionId);
    if (removed) {
      await this.removeSessionOrganization(sessionId);
    }
    return removed;
  }

  /**
   * Usage salvage wrapper enforcing the "never blocks deletion" contract at
   * the call site: persistUsageBeforeTranscriptDeletion catches its own
   * errors, but this second layer keeps the guarantee structural rather
   * than an implementation detail of another module.
   */
  private async salvageUsageBestEffort(transcriptPath: string): Promise<void> {
    try {
      await persistUsageBeforeTranscriptDeletion(transcriptPath);
    } catch (error) {
      this.warn(
        `usage salvage failed for ${transcriptPath}: ${error}; deleting anyway`,
      );
    }
  }

  private async removeSessionFiles(sessionId: string): Promise<boolean> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return false;
    }

    try {
      const activePath = this.getSessionFilePath(sessionId, 'active');
      const active = await this.readProjectSessionHead(sessionId, activePath);
      if (active) {
        // #7384: the usage-history rebuild reads transcripts, so salvage
        // the session's usage summary before the file is gone. Never
        // blocks deletion (the salvage swallows its own errors).
        await this.salvageUsageBestEffort(activePath);
        this.removeFileIfExists(activePath);
        const archivedPath = this.getSessionFilePath(sessionId, 'archived');
        if (fs.existsSync(archivedPath)) {
          // When both copies co-exist (e.g. an interrupted archive), the
          // active transcript may hold no telemetry while the archived one
          // carries the session's history — salvage it too. The dedup
          // guard inside the salvage makes this a no-op whenever the
          // active copy already produced a record.
          await this.salvageUsageBestEffort(archivedPath);
          this.removeFileIfExists(archivedPath);
        }
        this.removeWorktreeSidecars(sessionId);
        this.removeFileHistoryBackups(sessionId);
        return true;
      }
      const archivedPath = this.getSessionFilePath(sessionId, 'archived');
      const archived = await this.readProjectSessionHead(
        sessionId,
        archivedPath,
      );
      if (!archived) {
        return false;
      }
      await this.salvageUsageBestEffort(archivedPath);
      this.removeFileIfExists(archivedPath);
      this.removeWorktreeSidecars(sessionId);
      this.removeFileHistoryBackups(sessionId);
      return true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return false;
      }
      throw error;
    }
  }

  async archiveSessions(
    sessionIds: string[],
    options: ArchiveSessionsOptions = {},
  ): Promise<ArchiveSessionsResult> {
    const archived: string[] = [];
    const alreadyArchived: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    for (const sessionId of [...new Set(sessionIds)]) {
      try {
        if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
          notFound.push(sessionId);
          continue;
        }
        if (options.knownLocation !== 'active') {
          const location = await this.getSessionLocation(sessionId);
          if (location === undefined) {
            notFound.push(sessionId);
            continue;
          }
          if (location === 'archived') {
            alreadyArchived.push(sessionId);
            continue;
          }
          if (location === 'conflict') {
            throw new Error(`Session archive conflict: ${sessionId}`);
          }
        }

        const sourcePath = this.getSessionFilePath(sessionId, 'active');
        const targetPath = this.getSessionFilePath(sessionId, 'archived');
        if (fs.existsSync(targetPath)) {
          throw new Error(`Session archive conflict: ${sessionId}`);
        }

        fs.mkdirSync(this.getArchiveChatsDir(), { recursive: true });
        const activeSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'active',
        );
        const archivedSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'archived',
        );
        try {
          fs.renameSync(sourcePath, targetPath);
        } catch (error) {
          throw this.sessionFileMoveError('archive', error);
        }
        try {
          this.moveOptionalFile(activeSidecar, archivedSidecar);
        } catch (sidecarError) {
          this.warn(
            `archiveSessions: failed to move worktree sidecar for ${sessionId} from ${activeSidecar} to ${archivedSidecar}: ${sidecarError}`,
          );
        }
        archived.push(sessionId);
      } catch (error) {
        errors.push({
          sessionId,
          error: error instanceof Error ? error : new Error(String(error)),
        });
      }
    }

    return { archived, alreadyArchived, notFound, errors };
  }

  async unarchiveSessions(
    sessionIds: string[],
    options: UnarchiveSessionsOptions = {},
  ): Promise<UnarchiveSessionsResult> {
    const unarchived: string[] = [];
    const alreadyActive: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    for (const sessionId of [...new Set(sessionIds)]) {
      try {
        if (options.knownLocation !== 'archived') {
          const location = await this.getSessionLocation(sessionId);
          if (location === undefined) {
            notFound.push(sessionId);
            continue;
          }
          if (location === 'active') {
            alreadyActive.push(sessionId);
            continue;
          }
          if (location === 'conflict') {
            throw new Error(`Session archive conflict: ${sessionId}`);
          }
        }

        const sourcePath = this.getSessionFilePath(sessionId, 'archived');
        const targetPath = this.getSessionFilePath(sessionId, 'active');
        if (fs.existsSync(targetPath)) {
          throw new Error(`Session archive conflict: ${sessionId}`);
        }

        const archivedSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'archived',
        );
        const activeSidecar = this.getWorktreeSessionPathForState(
          sessionId,
          'active',
        );
        fs.mkdirSync(path.dirname(targetPath), { recursive: true });
        try {
          fs.renameSync(sourcePath, targetPath);
        } catch (error) {
          throw this.sessionFileMoveError('unarchive', error);
        }
        try {
          this.moveOptionalFile(archivedSidecar, activeSidecar);
        } catch (sidecarError) {
          this.warn(
            `unarchiveSessions: failed to move worktree sidecar for ${sessionId} from ${archivedSidecar} to ${activeSidecar}: ${sidecarError}`,
          );
        }
        unarchived.push(sessionId);
      } catch (error) {
        errors.push({
          sessionId,
          error: error instanceof Error ? error : new Error(String(error)),
        });
      }
    }

    return { unarchived, alreadyActive, notFound, errors };
  }

  /**
   * Removes multiple sessions in one call.
   *
   * Each session is processed independently — a failure on one does not
   * abort the rest. Sessions that don't exist (or belong to a different
   * project) are reported in {@link notFound}; thrown filesystem
   * errors are surfaced per-id in {@link errors} so callers can decide
   * whether to retry.
   *
   * @param sessionIds IDs to remove. Duplicates are de-duplicated.
   * @returns Per-id outcomes: which were removed, which were not found,
   *   and which threw an error.
   */
  async removeSessions(sessionIds: string[]): Promise<RemoveSessionsResult> {
    const removed: string[] = [];
    const notFound: string[] = [];
    const errors: Array<{ sessionId: string; error: Error }> = [];

    const uniqueSessionIds = [...new Set(sessionIds)];
    const results = await Promise.allSettled(
      uniqueSessionIds.map((sessionId) => this.removeSessionFiles(sessionId)),
    );

    for (let i = 0; i < results.length; i++) {
      const sessionId = uniqueSessionIds[i];
      if (sessionId === undefined) continue;

      const result = results[i];
      if (result.status === 'fulfilled') {
        if (result.value) {
          removed.push(sessionId);
        } else {
          notFound.push(sessionId);
        }
      } else {
        errors.push({ sessionId, error: result.reason as Error });
      }
    }

    await this.removeSessionOrganizations(removed);

    return { removed, notFound, errors };
  }

  /**
   * Renames a session by appending a custom_title system record to its JSONL file.
   *
   * @param sessionId The session ID to rename
   * @param title The new custom title
   * @param titleSource Where the title came from. Defaults to `'manual'` so
   *   existing callers are unchanged — pass `'auto'` only for titles produced
   *   by the auto-title generator.
   * @param archiveState Which session store to rename. Defaults to active.
   * @returns true if renamed successfully, false if session not found
   */
  async renameSession(
    sessionId: string,
    title: string,
    titleSource: TitleSource = 'manual',
    archiveState: SessionArchiveState = 'active',
  ): Promise<boolean> {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return false;
    }
    const filePath = this.getSessionFilePath(sessionId, archiveState);

    try {
      // Verify the file exists and belongs to this project
      const records = await jsonl.readLines<ChatRecord>(filePath, 1);
      if (records.length === 0) {
        return false;
      }

      if (
        !(await this.sessionBelongsToCurrentProject(sessionId, records[0].cwd))
      ) {
        return false;
      }

      // Read the last record's UUID so the custom_title record is properly
      // chained into the parent history.  reconstructHistory() walks from the
      // tail record upward via parentUuid; a null parentUuid would sever the
      // chain and cause the session to appear empty on next load.
      const lastUuid = this.readLastRecordUuid(filePath);

      // Append a custom_title system record. `renameSession` is the
      // fallback path when no live recording service is attached (e.g., from
      // the WebUI or VSCode extension). Callers pass `titleSource='auto'`
      // only when the title came from the auto-generator; defaults to
      // 'manual' for explicit user renames.
      const titleRecord: ChatRecord = {
        uuid: randomUUID(),
        parentUuid: lastUuid,
        sessionId,
        timestamp: new Date().toISOString(),
        type: 'system',
        subtype: 'custom_title',
        cwd: records[0].cwd,
        version: records[0].version,
        systemPayload: { customTitle: title, titleSource },
      };
      jsonl.writeLineSync(filePath, titleRecord);
      return true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return false;
      }
      throw error;
    }
  }

  /**
   * Forks a session to a new sessionId.
   *
   * Reads the source JSONL into memory, reconstructs the active record chain,
   * rewrites every record's `sessionId` to `newSessionId`, stamps `cwd` to this
   * service's project root, rebuilds the `parentUuid` chain so the fork is a
   * linear continuation, stamps `forkedFrom: { sessionId, messageUuid }` on
   * every copied record for audit, and writes the result to `<newId>.jsonl`.
   *
   * Mirrors Claude Code's `/branch` storage model: full in-memory copy + per-
   * message forkedFrom (see claude-code/src/commands/branch/branch.ts).
   *
   * The source file is not modified.
   *
   * @throws If source does not exist, source is empty, source belongs to a
   *   different project, or the target file already exists.
   * @remarks Only checks active source sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async forkSession(
    sourceSessionId: string,
    newSessionId: string,
    options: ForkSessionOptions = {},
  ): Promise<{ filePath: string; copiedCount: number }> {
    if (!SESSION_FILE_PATTERN.test(`${sourceSessionId}.jsonl`)) {
      throw new Error(`Invalid source sessionId: ${sourceSessionId}`);
    }
    if (!SESSION_FILE_PATTERN.test(`${newSessionId}.jsonl`)) {
      throw new Error(`Invalid new sessionId: ${newSessionId}`);
    }

    const chatsDir = this.getChatsDir();
    const sourcePath = path.join(chatsDir, `${sourceSessionId}.jsonl`);
    const targetPath = path.join(chatsDir, `${newSessionId}.jsonl`);

    // Read + parse the full source transcript.
    const records = await jsonl.read<ChatRecord>(sourcePath);
    if (records.length === 0) {
      throw new Error(`Source session not found or empty: ${sourceSessionId}`);
    }

    if (
      !(await this.sessionBelongsToCurrentProject(
        sourceSessionId,
        records[0].cwd,
      ))
    ) {
      throw new Error(
        `Source session does not belong to current project: ${sourceSessionId}`,
      );
    }

    const { messages: currentActiveMessages } =
      this.reconstructHistory(records);
    let boundedRecords = records;
    let activeMessages = currentActiveMessages;
    if (options.atRecordId !== undefined) {
      const point = resolveBranchPoints(currentActiveMessages).get(
        options.atRecordId,
      );
      if (!point) throw new BranchPointInvalidError(options.atRecordId);
      // The active chain merges duplicate uuids first-wins, so a checkpoint
      // line repeated by a crash-retry still resolves above. Bound the raw
      // prefix at the first occurrence: that is where the logical checkpoint
      // committed, and anything written after it must not leak into the fork.
      const matchingIndex = records.findIndex(
        (record) => record.uuid === options.atRecordId,
      );
      if (matchingIndex < 0) {
        throw new BranchPointInvalidError(options.atRecordId);
      }
      boundedRecords = records.slice(0, matchingIndex + 1);
      activeMessages = this.reconstructHistory(boundedRecords, {
        leafUuid: options.atRecordId,
      }).messages;
      if (activeMessages.at(-1)?.uuid !== options.atRecordId) {
        throw new BranchPointInvalidError(options.atRecordId);
      }
    }

    // Copy only the selected active branch. Rewind leaves old records in the
    // JSONL as abandoned parentUuid branches; copying raw records would
    // resurrect them. The raw input is physically bounded first so side
    // artifacts after a historical checkpoint cannot leak into the fork.
    const preFilterRecords = includeActiveSideArtifactRecords(
      boundedRecords,
      activeMessages,
    );
    const sourceRecords = preFilterRecords.filter(
      // A fork is a fresh top-level session with its own creation metadata.
      // Inheriting either record would falsely attribute the fork to the
      // source session's parent or creator.
      (record) =>
        !(
          record.type === 'system' &&
          (record.subtype === 'parent_session' ||
            record.subtype === 'session_source' ||
            record.subtype === 'turn_result' ||
            (options.source && record.subtype === 'custom_title'))
        ),
    );
    if (sourceRecords.length === 0) {
      throw new Error(`Source session not found or empty: ${sourceSessionId}`);
    }

    // Rebuild the parentUuid chain in active-history order so the fork is a
    // clean linear descendant. `forkedFrom` captures the origin of each
    // message.
    const sourceRecord: ChatRecord | undefined = options.source
      ? {
          uuid: randomUUID(),
          parentUuid: null,
          sessionId: newSessionId,
          timestamp: new Date().toISOString(),
          type: 'system',
          subtype: 'session_source',
          cwd: this.projectRoot,
          version: records[0].version,
          systemPayload: {
            sourceType: options.source.sourceType,
            ...(options.source.sourceId !== undefined
              ? { sourceId: options.source.sourceId }
              : {}),
          },
        }
      : undefined;
    let prevUuid: string | null = sourceRecord?.uuid ?? null;
    const remappedArtifactIds = new Map<string, string>();
    const retainedUuids = new Set(sourceRecords.map((record) => record.uuid));
    // Map filtered record UUIDs to their nearest retained predecessor so
    // checkpoint boundaries that pointed at a filtered creation/title record
    // are remapped rather than widened to the whole chain.
    const nearestRetainedPredecessor = new Map<string, string | null>();
    {
      let lastRetained: string | null = null;
      for (const record of preFilterRecords) {
        if (
          retainedUuids.has(record.uuid) &&
          !isSessionArtifactRecord(record)
        ) {
          lastRetained = record.uuid;
        } else {
          nearestRetainedPredecessor.set(record.uuid, lastRetained);
        }
      }
    }
    const forked: ChatRecord[] = [
      ...(sourceRecord ? [sourceRecord] : []),
      ...sourceRecords.map((record) => {
        const isArtifactRecord = isSessionArtifactRecord(record);
        let systemPayload = remapSystemPayloadForFork(
          record,
          sourceSessionId,
          newSessionId,
          remappedArtifactIds,
        );
        if (record.subtype === 'branch_checkpoint') {
          const checkpoint = parseBranchCheckpointPayload(systemPayload);
          if (checkpoint) {
            let boundary = checkpoint.startExclusiveRecordUuid;
            if (boundary !== null && !retainedUuids.has(boundary)) {
              boundary = nearestRetainedPredecessor.get(boundary) ?? null;
            }
            systemPayload = {
              ...checkpoint,
              startExclusiveRecordUuid: boundary,
            };
          }
        }
        const next: ChatRecord = {
          ...record,
          sessionId: newSessionId,
          cwd: this.projectRoot,
          systemPayload,
          parentUuid:
            isArtifactRecord &&
            record.parentUuid !== null &&
            retainedUuids.has(record.parentUuid)
              ? record.parentUuid
              : prevUuid,
          forkedFrom: {
            sessionId: sourceSessionId,
            messageUuid: record.uuid,
          },
        };
        if (!isArtifactRecord) {
          prevUuid = record.uuid;
        }
        return next;
      }),
    ];

    // File-history snapshots are side-channel system records used by /rewind.
    // They may not sit on the active message leaf copied above, and copied
    // records may still point at the source session's prompt ids. Remap and
    // top up snapshots explicitly so /branch sessions expose /rewind/snapshots
    // immediately after they become live.
    const sourceSession =
      options.atRecordId === undefined
        ? await this.loadSession(sourceSessionId)
        : undefined;
    const existingSnapshotPromptIds =
      collectFileHistorySnapshotPromptIds(forked);
    const remappedSnapshots = sourceSession?.fileHistorySnapshots
      ?.map((snapshot) =>
        remapSnapshotPromptId(snapshot, sourceSessionId, newSessionId),
      )
      .filter((snapshot) => !existingSnapshotPromptIds.has(snapshot.promptId));
    if (remappedSnapshots?.length) {
      const snapshotRecord: ChatRecord = {
        uuid: randomUUID(),
        parentUuid: prevUuid,
        sessionId: newSessionId,
        type: 'system',
        subtype: 'file_history_snapshot',
        timestamp: new Date().toISOString(),
        cwd: this.projectRoot,
        version: records[0].version,
        systemPayload: {
          snapshots: remappedSnapshots.map(serializeSnapshot),
        },
      };
      forked.push(snapshotRecord);
      prevUuid = snapshotRecord.uuid;
    }

    if (options.title !== undefined) {
      const titleRecord: ChatRecord = {
        uuid: randomUUID(),
        parentUuid: prevUuid,
        sessionId: newSessionId,
        type: 'system',
        subtype: 'custom_title',
        timestamp: new Date().toISOString(),
        cwd: this.projectRoot,
        version: records[0].version,
        systemPayload: {
          customTitle: options.title,
          titleSource: 'manual',
        },
      };
      forked.push(titleRecord);
      prevUuid = titleRecord.uuid;
    }

    const validateTargetBranchPoint = () => {
      if (options.atRecordId === undefined) return;
      const targetActive = this.reconstructHistory(forked).messages;
      if (!resolveBranchPoints(targetActive).has(options.atRecordId)) {
        throw new BranchPointInvalidError(options.atRecordId);
      }
    };
    validateTargetBranchPoint();

    const body = forked.map((r) => JSON.stringify(r)).join('\n') + '\n';
    const operationId = randomUUID();
    const stagedTranscriptPath = path.join(
      chatsDir,
      `.${newSessionId}.${operationId}.tmp`,
    );
    const backupRoot = path.join(Storage.getGlobalQwenDir(), FILE_HISTORY_DIR);
    const stagedBackupPath = path.join(
      backupRoot,
      `.${newSessionId}.${operationId}.tmp`,
    );
    const targetBackupPath = path.join(backupRoot, newSessionId);
    const backupNames = collectReferencedFileHistoryBackupNames(forked);

    await Promise.all([
      fs.promises.mkdir(chatsDir, { recursive: true }),
      fs.promises.mkdir(backupRoot, { recursive: true, mode: 0o700 }),
    ]);

    let backupPublished = false;
    let committed = false;
    try {
      if (
        (await pathExists(targetPath)) ||
        (await pathExists(targetBackupPath))
      ) {
        throw new Error(`Target session already exists: ${newSessionId}`);
      }

      const stagedHandle = await fs.promises.open(
        stagedTranscriptPath,
        'wx',
        0o600,
      );
      try {
        await stagedHandle.writeFile(body, { encoding: 'utf8' });
        await stagedHandle.sync();
      } finally {
        await stagedHandle.close();
      }

      if (backupNames.size > 0) {
        const copiedBackupNames = await copyFileHistoryBackupsToStaging(
          sourceSessionId,
          stagedBackupPath,
          backupNames,
          (name) => {
            this.warn(
              `branch ${newSessionId} omitted missing file-history backup ${name}; rewind data for that snapshot is unavailable`,
            );
          },
        );
        if (copiedBackupNames.size > 0) {
          if (await pathExists(targetBackupPath)) {
            throw new Error(`Target session already exists: ${newSessionId}`);
          }
          await fs.promises.rename(stagedBackupPath, targetBackupPath);
          backupPublished = true;
        }
      }

      try {
        await fs.promises.link(stagedTranscriptPath, targetPath);
      } catch (error) {
        const code = (error as NodeJS.ErrnoException).code;
        if (code === 'EEXIST') {
          throw new Error(`Target session already exists: ${newSessionId}`);
        }
        if (await pathExists(targetPath)) {
          throw new Error(`Target session already exists: ${newSessionId}`);
        }
        await fs.promises.rename(stagedTranscriptPath, targetPath);
      }
      committed = true;
      try {
        await fsyncDirectoryBestEffort(chatsDir);
      } catch (error) {
        this.warn(
          `branch committed session=${newSessionId} but final durability confirmation failed: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    } finally {
      const cleanupFailures: string[] = [];
      await fs.promises.unlink(stagedTranscriptPath).catch((error) => {
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
          cleanupFailures.push(`transcript staging: ${String(error)}`);
        }
      });
      await fs.promises
        .rm(stagedBackupPath, { recursive: true, force: true })
        .catch((error) => {
          cleanupFailures.push(`backup staging: ${String(error)}`);
        });
      if (!committed && backupPublished) {
        await fs.promises
          .rm(targetBackupPath, {
            recursive: true,
            force: true,
          })
          .catch((error) => {
            cleanupFailures.push(`published backup: ${String(error)}`);
          });
      }
      if (cleanupFailures.length > 0) {
        this.warn(
          `branch cleanup incomplete session=${newSessionId}: ${cleanupFailures.join('; ')}`,
        );
      }
    }

    return { filePath: targetPath, copiedCount: forked.length };
  }

  /**
   * Gets the custom title for a session by reading from its JSONL file.
   *
   * @param sessionId The session ID to look up
   * @returns The custom title, or undefined if none set
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitle(sessionId: string): string | undefined {
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return undefined;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);
    return this.readSessionTitleFromFile(filePath);
  }

  /**
   * Finds sessions by custom title.
   * Returns all matching sessions ordered by most recent first.
   *
   * @param title The custom title to search for (case-insensitive exact match)
   * @returns Array of matching session list items
   * @remarks Only searches active sessions. Archived title search is not
   * supported.
   */
  async findSessionsByTitle(title: string): Promise<SessionListItem[]> {
    const normalizedTitle = title.toLowerCase().trim();
    const matches: SessionListItem[] = [];
    const chatsDir = this.getChatsDir();

    // Scan all session files directly rather than paging through
    // listSessions(): the mtime-only cursor there uses a strict `<` boundary,
    // so sessions that share an mtime with the page's last entry are skipped,
    // which would silently drop valid title matches.
    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return matches;
      }
      throw error;
    }

    const files: Array<{ name: string; mtime: number }> = [];
    for (const name of fileNames) {
      if (!SESSION_FILE_PATTERN.test(name)) continue;
      const filePath = path.join(chatsDir, name);
      try {
        const stats = fs.statSync(filePath);
        files.push({ name, mtime: stats.mtimeMs });
      } catch {
        continue;
      }
    }

    // Sort most-recent first, with filename as a stable tie-breaker so runs
    // are deterministic even when multiple files share an mtime.
    files.sort((a, b) => b.mtime - a.mtime || a.name.localeCompare(b.name));

    // Pool the tail-read buffer across files; the title scan in the loop
    // body is otherwise the dominant alloc cost when many candidates exist.
    const tailBuffer = Buffer.alloc(LITE_READ_BUF_SIZE);

    let filesProcessed = 0;
    for (const file of files) {
      if (filesProcessed >= MAX_FILES_TO_PROCESS) break;
      filesProcessed++;

      const filePath = path.join(chatsDir, file.name);

      // Cheap check first: tail-read the title and skip non-matches before
      // doing the full hydration work (first-record read, project filter,
      // prompt extraction).
      const titleInfo = this.readSessionTitleInfoFromFile(filePath, tailBuffer);
      if (titleInfo.title?.toLowerCase().trim() !== normalizedTitle) continue;

      const records = await jsonl.readLines<ChatRecord>(
        filePath,
        MAX_PROMPT_SCAN_LINES,
      );
      if (records.length === 0) continue;
      const firstRecord = records[0];

      if (
        !(await this.sessionBelongsToCurrentProject(
          firstRecord.sessionId,
          firstRecord.cwd,
        ))
      ) {
        continue;
      }

      const prompt = this.extractFirstPromptFromRecords(records);

      matches.push({
        sessionId: firstRecord.sessionId,
        cwd: firstRecord.cwd,
        startTime: firstRecord.timestamp,
        mtime: file.mtime,
        prompt,
        gitBranch: firstRecord.gitBranch,
        filePath,
        // messageCount intentionally omitted; see SessionListItem for
        // the rationale and `countSessionMessages` for on-demand use.
        customTitle: titleInfo.title,
        titleSource: titleInfo.source,
      });
    }

    return matches;
  }

  /**
   * Returns the customTitles in this project that start with `prefix`
   * (case-insensitive). Single project-wide scan — meant to replace
   * repeated `findSessionsByTitle()` probes when the caller needs to
   * pick the first free `(Branch N)` slot in memory.
   *
   * Skips the heavy hydration steps (message count, prompt extraction)
   * that `findSessionsByTitle` does — collision lookup only needs the
   * title and a project filter, so we read the first record only when
   * the title actually matches the prefix.
   *
   * @param prefix Case-insensitive title prefix to match.
   */
  async findSessionTitlesByPrefix(prefix: string): Promise<string[]> {
    const normalizedPrefix = prefix.toLowerCase().trim();
    const titles: string[] = [];
    const chatsDir = this.getChatsDir();

    let fileNames: string[];
    try {
      fileNames = fs.readdirSync(chatsDir);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return titles;
      }
      throw error;
    }

    let filesProcessed = 0;
    for (const name of fileNames) {
      if (!SESSION_FILE_PATTERN.test(name)) continue;
      if (filesProcessed >= MAX_FILES_TO_PROCESS) break;
      filesProcessed++;

      const filePath = path.join(chatsDir, name);
      const titleInfo = this.readSessionTitleInfoFromFile(filePath);
      if (!titleInfo.title) continue;
      if (!titleInfo.title.toLowerCase().trim().startsWith(normalizedPrefix)) {
        continue;
      }

      try {
        const records = await jsonl.readLines<ChatRecord>(filePath, 1);
        if (records.length === 0) continue;
        if (
          !(await this.sessionBelongsToCurrentProject(
            records[0].sessionId,
            records[0].cwd,
          ))
        ) {
          continue;
        }
      } catch {
        continue;
      }
      titles.push(titleInfo.title);
    }

    return titles;
  }

  /**
   * Loads the most recent session for the current project.
   * Combines listSessions and loadSession for convenience.
   *
   * @returns Session data for resumption, or undefined if no sessions exist
   */
  async loadLastSession(): Promise<ResumedSessionData | undefined> {
    const result = await this.listSessions({ size: 1 });
    if (result.items.length === 0) {
      return;
    }
    return this.loadSession(result.items[0].sessionId);
  }

  /**
   * Checks if a session exists by its session ID.
   *
   * @param sessionId The session ID to check
   * @returns true if session exists and belongs to current project
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  async sessionExists(
    sessionId: string,
    options: { signal?: AbortSignal } = {},
  ): Promise<boolean> {
    options.signal?.throwIfAborted();
    if (!SESSION_FILE_PATTERN.test(`${sessionId}.jsonl`)) {
      return false;
    }
    const chatsDir = this.getChatsDir();
    const filePath = path.join(chatsDir, `${sessionId}.jsonl`);

    try {
      const records = options.signal
        ? await jsonl.readLines<ChatRecord>(filePath, 1, options)
        : await jsonl.readLines<ChatRecord>(filePath, 1);
      options.signal?.throwIfAborted();
      if (records.length === 0) {
        return false;
      }
      const belongsToCurrentProject = await this.sessionBelongsToCurrentProject(
        sessionId,
        records[0].cwd,
        options.signal,
      );
      options.signal?.throwIfAborted();
      return belongsToCurrentProject;
    } catch {
      options.signal?.throwIfAborted();
      return false;
    }
  }

  async sessionExistsInAnyState(sessionId: string): Promise<boolean> {
    try {
      const location = await this.getSessionLocation(sessionId);
      return location !== undefined;
    } catch {
      return true;
    }
  }
}

function remapSnapshotPromptId(
  snapshot: FileHistorySnapshot,
  sourceSessionId: string,
  newSessionId: string,
): FileHistorySnapshot {
  const sourcePrefix = `${sourceSessionId}########`;
  if (!snapshot.promptId.startsWith(sourcePrefix)) {
    return snapshot;
  }
  return {
    ...snapshot,
    promptId: `${newSessionId}########${snapshot.promptId.slice(sourcePrefix.length)}`,
  };
}

function remapFileHistorySnapshotPayload(
  payload: ChatRecord['systemPayload'],
  sourceSessionId: string,
  newSessionId: string,
): ChatRecord['systemPayload'] {
  const filePayload = payload as FileHistorySnapshotRecordPayload | undefined;
  if (!Array.isArray(filePayload?.snapshots)) return payload;

  try {
    const snapshots = deserializeSnapshots(filePayload.snapshots).map(
      (snapshot) =>
        serializeSnapshot(
          remapSnapshotPromptId(snapshot, sourceSessionId, newSessionId),
        ),
    );
    return { snapshots };
  } catch {
    return payload;
  }
}

function remapSystemPayloadForFork(
  record: ChatRecord,
  sourceSessionId: string,
  newSessionId: string,
  remappedArtifactIds: Map<string, string>,
): ChatRecord['systemPayload'] {
  if (record.type !== 'system') return record.systemPayload;
  if (record.subtype === 'file_history_snapshot') {
    return remapFileHistorySnapshotPayload(
      record.systemPayload,
      sourceSessionId,
      newSessionId,
    );
  }
  if (
    record.subtype === 'session_artifact_event' ||
    record.subtype === 'session_artifact_snapshot'
  ) {
    return remapSessionArtifactPayloadForFork(
      record.systemPayload,
      sourceSessionId,
      newSessionId,
      remappedArtifactIds,
    ) as ChatRecord['systemPayload'];
  }
  return record.systemPayload;
}

function includeActiveSideArtifactRecords(
  records: ChatRecord[],
  activeRecords: ChatRecord[],
): ChatRecord[] {
  const activeByUuid = new Map(
    activeRecords.map((record) => [record.uuid, record]),
  );
  const artifactUuids = new Set(
    selectActiveSideArtifactRecordUuids(
      records,
      activeRecords.map((record) => record.uuid),
    ),
  );
  const selected: ChatRecord[] = [];
  for (const record of records) {
    const activeRecord = activeByUuid.get(record.uuid);
    if (activeRecord) {
      selected.push(activeRecord);
      activeByUuid.delete(record.uuid);
      continue;
    }
    if (artifactUuids.has(record.uuid)) selected.push(record);
  }
  return selected;
}

function collectFileHistorySnapshotPromptIds(
  records: ChatRecord[],
): Set<string> {
  const ids = new Set<string>();
  for (const record of records) {
    if (
      record.type !== 'system' ||
      record.subtype !== 'file_history_snapshot' ||
      !record.systemPayload
    ) {
      continue;
    }
    const payload = record.systemPayload as FileHistorySnapshotRecordPayload;
    if (!Array.isArray(payload.snapshots)) continue;
    try {
      for (const snapshot of deserializeSnapshots(payload.snapshots)) {
        ids.add(snapshot.promptId);
      }
    } catch {
      // Malformed snapshot records are ignored the same way loadSession does.
    }
  }
  return ids;
}

function collectReferencedFileHistoryBackupNames(
  records: readonly ChatRecord[],
): Set<string> {
  const names = new Set<string>();
  for (const record of records) {
    if (
      record.type !== 'system' ||
      record.subtype !== 'file_history_snapshot' ||
      !record.systemPayload
    ) {
      continue;
    }
    const payload = record.systemPayload as FileHistorySnapshotRecordPayload;
    if (!Array.isArray(payload.snapshots)) continue;
    for (const snapshot of payload.snapshots) {
      if (
        !snapshot ||
        typeof snapshot !== 'object' ||
        !snapshot.trackedFileBackups ||
        typeof snapshot.trackedFileBackups !== 'object'
      ) {
        continue;
      }
      for (const backup of Object.values(snapshot.trackedFileBackups)) {
        if (
          backup &&
          backup.failed !== true &&
          typeof backup.backupFileName === 'string' &&
          backup.backupFileName.length > 0 &&
          backup.backupFileName !== '.' &&
          backup.backupFileName !== '..' &&
          path.basename(backup.backupFileName) === backup.backupFileName
        ) {
          names.add(backup.backupFileName);
        }
      }
    }
  }
  return names;
}

/**
 * Replays stored UI telemetry events to rebuild metrics when resuming a session.
 * Also restores the last prompt token count from the best available source.
 */
export function replayUiTelemetryFromConversation(
  conversation: ConversationRecord,
  sessionId?: string,
): ResumeTokenCounts | undefined {
  if (sessionId) {
    uiTelemetryService.resetSession(sessionId);
  } else {
    uiTelemetryService.reset();
  }

  for (const record of conversation.messages) {
    if (record.type !== 'system' || record.subtype !== 'ui_telemetry') {
      continue;
    }
    const payload = record.systemPayload as
      | UiTelemetryRecordPayload
      | undefined;
    const uiEvent = payload?.uiEvent;
    if (uiEvent) {
      uiTelemetryService.addEvent(uiEvent, sessionId);
    }
  }

  const resumeTokenCounts = getResumeTokenCounts(conversation);
  if (resumeTokenCounts !== undefined) {
    uiTelemetryService.setLastPromptTokenCount(
      resumeTokenCounts.promptTokenCount,
    );
  }
  return resumeTokenCounts;
}

const MAX_BRANCH_COLLISION_SCAN = 99;

export async function computeUniqueBranchTitle(
  baseName: string,
  sessionService: SessionService,
): Promise<string> {
  const maxSuffixLen = ' (Branch 1234567890123)'.length;
  const trimmed = baseName
    .trim()
    .slice(0, SESSION_TITLE_MAX_LENGTH - maxSuffixLen);
  const taken = new Set(
    (await sessionService.findSessionTitlesByPrefix(`${trimmed} (Branch`)).map(
      (t) => t.toLowerCase().trim(),
    ),
  );
  const first = `${trimmed} (Branch)`;
  if (!taken.has(first.toLowerCase())) return first;
  for (let n = 2; n <= MAX_BRANCH_COLLISION_SCAN; n++) {
    const candidate = `${trimmed} (Branch ${n})`;
    if (!taken.has(candidate.toLowerCase())) return candidate;
  }
  return `${trimmed} (Branch ${Date.now()})`;
}
