/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

export {
  DaemonClient,
  DaemonHttpError,
  DaemonPendingPromptLimitError,
  DaemonSessionIdProtocolError,
  EXTENSION_ARCHIVE_UPLOAD_TIMEOUT_MS,
  WorkspaceDaemonClient,
  isDaemonTurnError,
  isNonBlockingAccepted,
  isStaleBranchPointError,
  matchTurnEvent,
  type CreateSessionRequest,
  type DaemonClientOptions,
  type DaemonSseConnectReason,
  type DaemonTurnError,
  type NonBlockingPromptAccepted,
  type PromptRequest,
  type RestoreSessionRequest,
  type SubscribeOptions,
} from './DaemonClient.js';
export {
  isSessionLevelNotFound,
  isSubagentSessionNotFound,
} from './DaemonHttpError.js';
// Transport abstraction layer
export { DaemonTransportClosedError } from './DaemonTransport.js';
export type {
  DaemonTransport,
  DaemonTransportFetchOptions,
  DaemonTransportSubscribeOptions,
  DaemonTransportType,
} from './DaemonTransport.js';
export type { RestSseTransport } from './RestSseTransport.js';
// negotiateTransport + the concrete ACP transport classes are intentionally
// NOT re-exported here: a static import chain from this barrel would pull
// their framing/SSE code into the budget-checked browser bundle (see
// `scripts/build.js` MAX_DAEMON_BROWSER_BUNDLE_BYTES). They ship instead
// behind the opt-in `@qwen-code/sdk/daemon/transports` subpath
// (`./transports.ts`), so REST-only consumers stay tree-shaken while
// consumers who want resumable ACP-over-HTTP get a first-class import:
//   import { negotiateTransport, AcpHttpTransport }
//     from '@qwen-code/sdk/daemon/transports';
// The `NegotiateTransportOptions` *type* stays available from this barrel
// for backward compatibility (type-only, no bundle cost).
export type { NegotiateTransportOptions } from './negotiateTransport.js';
export type { JsonRpcNotification } from './AcpEventDenormalizer.js';
export type { TransportFactory } from './AutoReconnectTransport.js';
export {
  DaemonAuthFlow,
  DEVICE_FLOW_EXPIRY_GRACE_MS,
  type AwaitCompletionOptions,
  type DaemonAuthFlowHandle,
} from './DaemonAuthFlow.js';
export {
  DaemonSessionClient,
  type DaemonReplaySnapshot,
  type DaemonSessionClientOptions,
  type DaemonSessionSubscribeOptions,
} from './DaemonSessionClient.js';
export {
  asKnownDaemonEvent,
  DAEMON_KNOWN_EVENT_TYPE_VALUES,
  MID_TURN_MESSAGE_INJECTED_EVENT,
  PENDING_PROMPT_ADDED_EVENT,
  PENDING_PROMPT_STARTED_EVENT,
  PENDING_PROMPT_COMPLETED_EVENT,
  createDaemonAuthState,
  createDaemonSessionViewState,
  isDaemonEventType,
  isKnownDaemonEvent,
  // Re-export the workspace-scoped budget event helper. Previously
  // the event JSDoc told consumers to use this helper to branch on
  // `scope === 'workspace'`, but the function lived in `events.ts`
  // and was never added to this barrel — SDK consumers had no public
  // import path. Now locked down by `daemon-public-surface.test.ts`.
  isWorkspaceScopedBudgetEvent,
  reduceDaemonAuthEvent,
  reduceDaemonAuthEvents,
  reduceDaemonSessionEvent,
  reduceDaemonSessionEvents,
} from './events.js';
export { parseSseStream, SseFramingError } from './sse.js';
export {
  appendLocalUserTranscriptMessage,
  createDaemonToolPreview,
  createDaemonTranscriptState,
  createDaemonTranscriptStore,
  DAEMON_GOAL_STATUS_SENTINEL_PREFIX,
  DAEMON_PLAN_TOOL_CALL_ID,
  DAEMON_UI_DEBUG_REASONS,
  daemonBlockToHtml,
  daemonBlockToMarkdown,
  daemonBlockToPlainText,
  daemonToolPreviewToMarkdown,
  daemonUiEventToTerminalText,
  extractContentPart,
  extractServerTimestamp,
  formatBlockTimestamp,
  getOutputText as getDaemonUiOutputText,
  getSessionUpdatePayload,
  isDaemonUiSensitiveKey,
  isSubagentChildBlock,
  normalizeDaemonEvent,
  redactDaemonUiSensitiveFields,
  rebuildDaemonTranscriptBlockIndex,
  reduceDaemonTranscriptEvents,
  runAdapterConformanceSuite,
  sanitizeTerminalText as sanitizeDaemonTerminalText,
  selectApprovalMode,
  selectCurrentTool,
  selectLastFollowupSuggestion,
  selectPendingPermissionBlocks,
  selectSubagentChildBlocks,
  selectToolProgress,
  selectTranscriptBlocks,
  selectTranscriptBlocksOrderedByEventId,
  stringifyJson as stringifyDaemonUiJson,
  stripOscSequences as stripDaemonOscSequences,
  transcriptBlockToTerminalText,
  DAEMON_UI_CONFORMANCE_FIXTURES,
} from './ui/index.js';
export type {
  DaemonRenderOptions,
  DaemonHtmlRenderOptions,
  DaemonUiContentPart,
  DaemonUiAdapterUnderTest,
  DaemonUiConformanceFixture,
  ConformanceFailure,
  ConformanceSuiteResult,
  RunConformanceOptions,
} from './ui/index.js';
export type {
  DaemonShellTranscriptBlock,
  DaemonUserShellTranscriptBlock,
  DaemonPermissionTranscriptBlock,
  DaemonStatusTranscriptBlock,
  DaemonInputAnnotation,
  DaemonInputReference,
  DaemonInputReferenceAnnotation,
  DaemonTextTranscriptBlock,
  DaemonTextDeltaMeta,
  DaemonToolPreview,
  DaemonToolTranscriptBlock,
  DaemonTranscriptBlock,
  DaemonTranscriptBlockKind,
  DaemonTranscriptQuestion,
  DaemonTranscriptQuestionOption,
  DaemonTranscriptReducerOptions,
  DaemonTranscriptSidechannelState,
  DaemonTranscriptState,
  DaemonTranscriptStore,
  DaemonUiAssistantDoneEvent,
  DaemonUiAuthDeviceFlowAuthorizedEvent,
  DaemonUiAuthDeviceFlowCancelledEvent,
  DaemonUiAuthDeviceFlowEvent,
  DaemonUiAuthDeviceFlowFailedEvent,
  DaemonUiAuthDeviceFlowStartedEvent,
  DaemonUiAuthDeviceFlowThrottledEvent,
  DaemonUiDebugReason,
  DaemonUiErrorEvent,
  DaemonUiEvent,
  DaemonUiEventBase,
  DaemonUiEventType,
  DaemonUiMcpBudgetWarningEvent,
  DaemonUiMcpChildRefusedEvent,
  DaemonUiMcpServerRestartedEvent,
  DaemonUiMcpServerRestartRefusedEvent,
  DaemonUiMcpServerChangedEvent,
  DaemonUiModelChangedEvent,
  DaemonUiPermissionOption,
  DaemonUiPermissionRequestEvent,
  DaemonUiPermissionResolvedEvent,
  DaemonUiSessionActions,
  DaemonUiSessionApprovalModeChangedEvent,
  DaemonUiSessionAvailableCommandsEvent,
  DaemonUiSessionMetadataChangedEvent,
  DaemonUiShellOutputEvent,
  DaemonUiStateResyncRequiredEvent,
  DaemonUiReplayCompleteEvent,
  DaemonUiPromptCancelledEvent,
  DaemonUiFollowupSuggestionEvent,
  DaemonUiStatusEvent,
  DaemonUiTextEvent,
  DaemonUiToolProvenance,
  DaemonUiToolUpdateEvent,
  DaemonUiWorkspaceAgentChangedEvent,
  DaemonUiGithubSetupCompletedEvent,
  DaemonUiWorkspaceInitializedEvent,
  DaemonUiWorkspaceMemoryChangedEvent,
  DaemonUiWorkspaceToolToggledEvent,
  NormalizeDaemonEventOptions,
} from './ui/index.js';
export {
  DAEMON_APPROVAL_MODES,
  DAEMON_ERROR_KINDS,
  DaemonCapabilityMissingError,
  isDaemonContentHash,
  requireWorkspaceCwd,
} from './types.js';
export type {
  DaemonAgentChangedData,
  DaemonAgentChangedEvent,
  DaemonArtifactChangedData,
  DaemonArtifactChangedEvent,
  DaemonApprovalModeChangedData,
  DaemonApprovalModeChangedEvent,
  DaemonClientEvictedData,
  DaemonClientEvictedEvent,
  DaemonHistoryTruncatedData,
  DaemonHistoryTruncatedEvent,
  DaemonControlEvent,
  // Daemon-emitted resync
  // signal for SSE reconnects past the ring eviction boundary.
  DaemonStateResyncRequiredData,
  DaemonStateResyncRequiredEvent,
  DaemonMcpServerAddedData,
  DaemonMcpServerAddedEvent,
  DaemonMcpServerRemovedData,
  DaemonMcpServerRemovedEvent,
  DaemonMcpServerRestartedData,
  DaemonMcpServerRestartedEvent,
  DaemonMcpServerRestartRefusedData,
  DaemonMcpServerRestartRefusedEvent,
  DaemonMcpServerChangedData,
  DaemonMcpServerChangedEvent,
  DaemonSettingsReloadedData,
  DaemonSettingsReloadedEvent,
  DaemonSettingsChangedData,
  DaemonSettingsChangedEvent,
  DaemonSessionRewoundData,
  DaemonSessionRewoundEvent,
  DaemonSessionBranchedData,
  DaemonSessionBranchedEvent,
  DaemonToolToggledData,
  DaemonToolToggledEvent,
  DaemonTrustChangeRequestedData,
  DaemonTrustChangeRequestedEvent,
  DaemonGithubSetupCompletedData,
  DaemonGithubSetupCompletedEvent,
  DaemonWorkspaceInitializedData,
  DaemonWorkspaceInitializedEvent,
  DaemonEventEnvelope,
  DaemonKnownEventType,
  // MCP guardrail push-event types. See `mcp_guardrail_events`
  // capability tag and the `DaemonMcpGuardrailEvent` union below.
  DaemonMcpBudgetWarningData,
  DaemonMcpBudgetWarningEvent,
  DaemonMcpChildRefusedBatchData,
  DaemonMcpChildRefusedBatchEvent,
  DaemonMcpGuardrailEvent,
  DaemonMcpRefusedServer,
  DaemonFileMemoryChangedData,
  DaemonManagedMemoryChangedData,
  DaemonMemoryChangedData,
  DaemonMemoryChangedEvent,
  DaemonModelSwitchedData,
  DaemonModelSwitchedEvent,
  DaemonModelSwitchFailedData,
  DaemonModelSwitchFailedEvent,
  DaemonPermissionOption,
  DaemonPermissionAlreadyResolvedData,
  DaemonPermissionAlreadyResolvedEvent,
  // Multi-client permission coordination push events.
  DaemonPermissionForbiddenData,
  DaemonPermissionForbiddenEvent,
  DaemonPermissionPartialVoteData,
  DaemonPermissionPartialVoteEvent,
  DaemonPermissionRequestData,
  DaemonPermissionRequestEvent,
  DaemonPermissionResolvedData,
  DaemonPermissionResolvedEvent,
  DaemonSessionClosedData,
  DaemonSessionClosedEvent,
  DaemonSessionClosedReason,
  DaemonSessionDiedData,
  DaemonSessionDiedEvent,
  DaemonSessionEvent,
  DaemonSessionMetadataUpdatedData,
  DaemonSessionMetadataUpdatedEvent,
  DaemonSessionRecordingDegradedData,
  DaemonSessionRecordingDegradedEvent,
  DaemonMidTurnMessageInjectedData,
  DaemonMidTurnMessageInjectedEvent,
  DaemonPendingPromptAddedData,
  DaemonPendingPromptAddedEvent,
  DaemonPendingPromptStartedData,
  DaemonPendingPromptStartedEvent,
  DaemonPendingPromptCompletedData,
  DaemonPendingPromptCompletedEvent,
  DaemonPendingPromptEvent,
  DaemonSessionUpdateData,
  DaemonSessionUpdateEvent,
  DaemonSessionViewState,
  DaemonSlowClientWarningData,
  DaemonSlowClientWarningEvent,
  DaemonStreamErrorData,
  DaemonStreamErrorEvent,
  DaemonStreamLifecycleEvent,
  DaemonWorkspaceMutationEvent,
  DaemonAuthDeviceFlowProviderId,
  DaemonAuthDeviceFlowStatus,
  DaemonAuthDeviceFlowErrorKind,
  DaemonAuthDeviceFlowStartedData,
  DaemonAuthDeviceFlowStartedEvent,
  DaemonAuthDeviceFlowThrottledData,
  DaemonAuthDeviceFlowThrottledEvent,
  DaemonAuthDeviceFlowAuthorizedData,
  DaemonAuthDeviceFlowAuthorizedEvent,
  DaemonAuthDeviceFlowFailedData,
  DaemonAuthDeviceFlowFailedEvent,
  DaemonAuthDeviceFlowCancelledData,
  DaemonAuthDeviceFlowCancelledEvent,
  DaemonAuthEvent,
  // Daemon assist push (server-side ghost-text suggestion)
  DaemonAssistEvent,
  DaemonFollowupSuggestionData,
  DaemonFollowupSuggestionEvent,
  DaemonChannelDeliveryErrorCode,
  DaemonChannelDeliveryResultData,
  DaemonChannelDeliveryResultEvent,
  // Non-blocking prompt completion events
  DaemonTurnEvent,
  DaemonTurnCompleteData,
  DaemonTurnCompleteEvent,
  DaemonTurnErrorData,
  DaemonTurnErrorEvent,
  // A5 — side-channel session snapshot
  DaemonSessionSnapshotData,
  DaemonSessionSnapshotEvent,
  DaemonDeviceFlowReducerState,
  DaemonAuthState,
  KnownDaemonEvent,
} from './events.js';
export type {
  DaemonAgentLevel,
  DaemonAgentMutationResult,
  DaemonGeneratedAgentContent,
  DaemonWorkspaceGenerationEvent,
  DaemonApprovalMode,
  DaemonApprovalModeResult,
  DaemonGithubSetupGitignoreResult,
  DaemonGithubSetupRequest,
  DaemonGithubSetupResult,
  DaemonGithubSetupWorkflowResult,
  DaemonInitWorkspaceResult,
  DaemonMcpManageAction,
  DaemonMcpManageResult,
  DaemonMcpRestartResult,
  DaemonReloadResponse,
  DaemonChannelControlState,
  DaemonChannelControlTransition,
  DaemonChannelDelivery,
  DaemonChannelNotifyRequest,
  DaemonChannelNotifyResult,
  DaemonChannelReloadResult,
  DaemonChannelSelection,
  DaemonChannelSetResult,
  DaemonChannelStartupAttemptFailure,
  DaemonChannelStartupFailure,
  DaemonChannelStopResult,
  DaemonChannelWorkerStartErrorResponse,
  DaemonChannelConfigFieldKind,
  DaemonChannelConfigFieldDescriptor,
  DaemonChannelConfigValueFieldDescriptor,
  DaemonChannelConfigPlainValueFieldDescriptor,
  DaemonChannelConfigEnumFieldDescriptor,
  DaemonChannelConfigNumberFieldDescriptor,
  DaemonChannelConfigObjectFieldDescriptor,
  DaemonChannelConfigNestedFieldDescriptor,
  DaemonChannelTypeDescriptor,
  DaemonChannelTypeCatalog,
  DaemonChannelRuntimeState,
  DaemonChannelSecretState,
  DaemonChannelInstanceSnapshot,
  DaemonChannelsSnapshot,
  DaemonChannelSecretUpdate,
  DaemonRevisionRequest,
  DaemonChannelUpsertRequest,
  DaemonChannelStartupRequest,
  DaemonChannelMutationResult,
  DaemonChannelPairingRequest,
  DaemonChannelPairingSubject,
  DaemonChannelPairingRequestsSnapshot,
  DaemonChannelPairingApprovalRequest,
  DaemonChannelPairingApprovalResult,
  DaemonChannelPairingApprovalsSnapshot,
  DaemonChannelPairingRevocationRequest,
  DaemonChannelPairingRevocationResult,
  DaemonChannelManagementOptions,
  DaemonChannelWorkerGroupSnapshot,
  DaemonChannelWorkerSnapshot,
  DaemonRewindResult,
  DaemonRewindSnapshotInfo,
  DaemonSessionBtwResult,
  DaemonSessionGenerationEvent,
  DaemonMidTurnMessageResult,
  DaemonMidTurnMessageSummary,
  DaemonMidTurnMessagesResult,
  DaemonRemoveMidTurnMessageResult,
  DaemonPendingPromptSummary,
  DaemonPendingPromptsResult,
  DaemonRemovePendingPromptResult,
  DaemonSessionRecapResult,
  DaemonShellCommandResult,
  DaemonRuntimeMcpAddRequest,
  DaemonRuntimeMcpAddResult,
  DaemonRuntimeMcpRemoveResult,
  DaemonToolToggleResult,
  DaemonSkillBatchToggleError,
  DaemonSkillBatchToggleErrorCode,
  DaemonSkillBatchToggleItem,
  DaemonSkillBatchToggleResult,
  DaemonSkillToggleActivation,
  DaemonSkillToggleMutation,
  DaemonSkillToggleMutationSkill,
  DaemonSkillToggleResult,
  DaemonSkillScope,
  DaemonSkillInstallSource,
  DaemonSkillInstallRequest,
  DaemonSkillMutationResult,
  DaemonSettingDescriptor,
  DaemonPermissionRuleSet,
  DaemonPermissionRuleType,
  DaemonPermissionScope,
  DaemonWorkspacePermissionScopeState,
  DaemonWorkspacePermissionsStatus,
  DaemonWorkspaceSettingsStatus,
  DaemonSettingUpdateResult,
  DaemonModelDeleteRequest,
  DaemonModelDeleteResult,
  DaemonVoiceAudioInput,
  DaemonVoiceMode,
  DaemonVoiceModelDescriptor,
  DaemonVoiceTransport,
  DaemonWorkspaceVoiceStatus,
  DaemonWorkspaceVoiceTranscribeOptions,
  DaemonWorkspaceVoiceTranscriptionResult,
  DaemonWorkspaceVoiceUpdate,
  DaemonLiveBlocker,
  DaemonLiveHostInstallState,
  DaemonLiveHostInstallStatus,
  DaemonLiveMuteUpdate,
  DaemonLiveRequirementState,
  DaemonLiveSetupApiKeyMutation,
  DaemonLiveSetupStatus,
  DaemonLiveSetupUpdate,
  DaemonLiveState,
  DaemonLiveStatus,
  DaemonWorkspaceTrustChangeRequest,
  DaemonWorkspaceTrustChangeResult,
  DaemonWorkspaceTrustDesiredState,
  DaemonWorkspaceTrustLevel,
  DaemonWorkspaceTrustSource,
  DaemonWorkspaceTrustState,
  DaemonWorkspaceTrustStatus,
  DaemonWorkspaceTrustStatusResponse,
  DaemonWorkspaceTrustStatusV2,
  DaemonWorkspaceTrustReconciliationState,
  DaemonWorkspaceCapability,
  DaemonWorkspaceUpdate,
  DaemonWorkspaceGitStatus,
  DaemonGitOperation,
  DaemonWorkspaceGitDiff,
  DaemonWorkspaceGitDiffFile,
  DaemonWorkspaceGitDiffHunks,
  DaemonDiffHunk,
  DaemonGitLogEntry,
  DaemonGitLog,
  DaemonGitCommitFileStat,
  DaemonGitCommitDetail,
  DaemonGitBranchInfo,
  DaemonGitTagInfo,
  DaemonGitBranchesResult,
  DaemonGitCheckoutResult,
  DaemonGitPushResult,
  DaemonGitPullResult,
  DaemonGitCommitResult,
  DaemonGitHubPullRequestReviewDecision,
  DaemonGitHubPullRequestChecks,
  DaemonGitHubPullRequest,
  DaemonGitHubPullRequestList,
  DaemonGitHubPullRequestCreateResult,
  DaemonWorkspaceRemovalActivity,
  DaemonWorkspaceRemovalResult,
  DaemonAvailableCommand,
  DaemonArchiveSessionsResult,
  DaemonCapabilities,
  DaemonContextCategoryBreakdown,
  DaemonContextFileScope,
  DaemonContextMemoryDetail,
  DaemonContextSkillDetail,
  DaemonContextToolDetail,
  DaemonCreateAgentRequest,
  DaemonEnvCell,
  DaemonEnvKind,
  DaemonErrorKind,
  DaemonEvent,
  DaemonMcpDiscoveryState,
  DaemonMcpServerRuntimeStatus,
  DaemonMcpTransport,
  DaemonMode,
  DaemonProtocolVersions,
  BranchSessionRequest,
  DaemonBranchSessionRequest,
  DaemonBranchSessionResult,
  DaemonBranchedSession,
  HistoricalBranchSessionRequest,
  DaemonPersistedBranchedSession,
  DaemonSideTaskSession,
  DaemonForkSessionResult,
  ForkSessionRequest,
  SideTaskSessionRequest,
  DaemonRestoredSession,
  DaemonSession,
  DaemonSessionArchiveState,
  DaemonWorktreeInfo,
  DaemonBranchInfo,
  DaemonBranchPoint,
  DaemonSessionExportFormat,
  DaemonSessionExportResult,
  DaemonSessionTranscriptPage,
  DaemonSessionTranscriptPageOptions,
  DaemonAuthProviderId,
  DaemonAuthProviderBaseUrlOption,
  DaemonAuthProviderCatalog,
  DaemonAuthProviderDescriptor,
  DaemonAuthProviderInstallRequest,
  DaemonAuthProviderInstallResult,
  DaemonAuthProviderModel,
  DaemonAuthDeviceFlowSdkStatus,
  DaemonAuthDeviceFlowSdkErrorKind,
  DaemonAuthProviderStatus,
  DaemonAuthStatusSnapshot,
  DaemonDeviceFlowStartResult,
  DaemonDeviceFlowState,
  DaemonSessionContextStatus,
  DaemonLspServerStatus,
  DaemonSessionLspStatus,
  DaemonSessionAgentTaskStatus,
  DaemonSessionMonitorTaskStatus,
  DaemonSessionProcessTaskLifecycleStatus,
  DaemonSessionContextUsage,
  DaemonSessionContextUsageStatus,
  DaemonSessionGroup,
  DaemonSessionGroupCatalog,
  DaemonSessionGroupColor,
  DaemonSessionGroupHexColor,
  DaemonSessionGroupPresetColor,
  DaemonSessionGroupFilter,
  DaemonSessionGroupInput,
  DaemonSessionGroupUpdate,
  DaemonSessionListPage,
  DaemonSessionListPageOptions,
  DaemonSessionListView,
  DaemonWorkspaceSessionInfo,
  DaemonSessionCatalogVersion,
  DaemonSessionLiveState,
  DaemonWorkspaceSessionLiveState,
  DaemonSessionOrganizationResult,
  DaemonSessionOrganizationUpdate,
  DaemonPendingInteraction,
  DaemonPendingInteractionOption,
  DaemonPendingPermissionInteraction,
  DaemonPendingUserQuestion,
  DaemonPendingUserQuestionInteraction,
  DaemonSessionState,
  DaemonSessionSummary,
  DaemonSessionShellTaskStatus,
  DaemonSessionSupportedCommandsStatus,
  DaemonSessionTaskLifecycleStatus,
  DaemonSessionTaskStatus,
  DaemonSessionTasksStatus,
  DaemonSessionStatsStatus,
  DaemonSessionStatsModelMetrics,
  DaemonSessionStatsToolByName,
  DaemonUsageRange,
  DaemonUsageDashboard,
  DaemonUsageDashboardTotals,
  DaemonUsageModelShare,
  DaemonUsageSkillCall,
  DaemonUsageDailyPoint,
  DaemonUsageHeatmapDay,
  DaemonSkillLevel,
  DaemonPreflightCell,
  DaemonPreflightKind,
  DaemonStatus,
  DaemonStatusCell,
  DaemonLogHealth,
  DaemonLogIssue,
  DaemonLogMode,
  DaemonStatusReport,
  DaemonStatusReportDetail,
  DaemonStatusReportIssue,
  DaemonStatusReportLevel,
  DaemonStatusReportSection,
  DaemonStatusReportSession,
  DaemonMetricsSeriesBucket,
  DaemonUpdateAgentRequest,
  DaemonContentHash,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceAgentsStatus,
  DaemonWorkspaceEnvStatus,
  DaemonWorkspaceFile,
  DaemonWorkspaceFileBytes,
  DaemonWorkspaceFileEditRequest,
  DaemonWorkspaceFileEditResult,
  DaemonWorkspaceFileUploadRequest,
  DaemonWorkspaceFileUploadResult,
  DaemonWorkspaceFileWriteRequest,
  DaemonWorkspaceFileWriteResult,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpStatus,
  DaemonWorkspaceMcpInitializeResult,
  DaemonWorkspaceMcpReloadOptions,
  DaemonWorkspaceMcpToolStatus,
  DaemonWorkspaceMcpToolsStatus,
  DaemonWorkspaceMcpResourceStatus,
  DaemonWorkspaceMcpResourcesStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceMemoryStatus,
  DaemonWorkspaceMemoryDreamOptions,
  DaemonWorkspaceMemoryDreamResult,
  DaemonWorkspaceMemoryDreamTask,
  DaemonWorkspaceMemoryForgetMatch,
  DaemonWorkspaceMemoryForgetOptions,
  DaemonWorkspaceMemoryForgetResult,
  DaemonWorkspaceMemoryForgetTask,
  DaemonWorkspaceMemoryRememberContextMode,
  DaemonWorkspaceMemoryRememberOptions,
  DaemonWorkspaceMemoryRememberResult,
  DaemonWorkspaceMemoryRememberTask,
  DaemonWorkspaceMemoryRememberTaskStatus,
  DaemonWorkspaceMemoryTaskStatus,
  DaemonWorkspaceMemoryTopic,
  DaemonWorkspacePreflightStatus,
  DaemonWorkspaceAcpStatusResult,
  DaemonWorkspaceAcpPreheatResult,
  DaemonWorkspaceProviderCurrent,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceSkillsStatus,
  DaemonWorkspaceToolStatus,
  DaemonWorkspaceToolsStatus,
  DaemonWriteMemoryRequest,
  DaemonWriteMemoryResult,
  DaemonUnarchiveSessionsResult,
  DaemonCommandHookConfig,
  DaemonFunctionHookConfig,
  DaemonHookConfig,
  DaemonHookEntry,
  DaemonHookEventMeta,
  DaemonHookEventName,
  DaemonHookMatcherKind,
  DaemonHookSource,
  DaemonHttpHookConfig,
  DaemonPromptHookConfig,
  DaemonSessionHooksStatus,
  DaemonUnknownHookConfig,
  DaemonWorkspaceHooksStatus,
  DaemonExtensionInstallType,
  DaemonExtensionOriginSource,
  DaemonExtensionCapabilities,
  DaemonExtensionDetails,
  DaemonExtensionEntry,
  DaemonExtensionUpdateState,
  DaemonWorkspaceExtensionsStatus,
  ExtensionInstallRequest,
  ExtensionArchiveInstallRequest,
  ExtensionManagementInstallRequest,
  ExtensionInitialActivation,
  ExtensionActivationState,
  ExtensionWorkspaceActivation,
  ExtensionCatalogEntry,
  ExtensionCatalog,
  WorkspaceExtensionProjectionEntry,
  WorkspaceExtensionProjection,
  ExtensionInstallResponse,
  ExtensionInteractionResponse,
  ExtensionInteractionResponseResult,
  ExtensionMutationResponse,
  ExtensionPendingInteraction,
  ExtensionMarketplacePluginInteraction,
  ExtensionSettingInteraction,
  ExtensionOperationResult,
  ExtensionOperationState,
  ExtensionOperationStatus,
  ExtensionActiveOperations,
  ExtensionRefreshResponse,
  ExtensionScope,
  ExtensionScopeRequest,
  ExtensionUpdateCheckResponse,
  HeartbeatResult,
  MCPServerConfigShape,
  PermissionOutcome,
  PermissionOutcomeCancelled,
  PermissionOutcomeSelected,
  PermissionResponse,
  PromptContentBlock,
  DaemonSessionMediaData,
  DaemonSessionMediaReference,
  PromptResult,
  PromptTextContent,
  SetModelResult,
  DaemonSessionConfigOptionResult,
  SetSessionLanguageResult,
  KnownDaemonSessionArtifactChangeAction,
  KnownDaemonSessionArtifactKind,
  KnownDaemonSessionArtifactPersistenceWarning,
  KnownDaemonSessionArtifactRemovalReason,
  KnownDaemonSessionArtifactRestoreState,
  KnownDaemonSessionArtifactRetention,
  KnownDaemonSessionArtifactSource,
  KnownDaemonSessionArtifactStatus,
  KnownDaemonSessionArtifactStorage,
  DaemonSessionArtifact,
  DaemonSessionArtifactChange,
  DaemonSessionArtifactChangeAction,
  DaemonSessionArtifactInput,
  DaemonSessionArtifactKind,
  DaemonSessionArtifactMutationResult,
  DaemonSessionArtifactPersistenceWarning,
  DaemonSessionArtifactRemovalReason,
  DaemonSessionArtifactRestoreState,
  DaemonSessionArtifactRetention,
  DaemonSessionArtifactsEnvelope,
  DaemonSessionArtifactSource,
  DaemonSessionArtifactStatus,
  DaemonSessionArtifactStorage,
  SessionMetadataResult,
} from './types.js';
