export { query } from './query/createQuery.js';
export { AbortError, isAbortError } from './types/errors.js';
export { Query } from './query/Query.js';
export { SdkLogger } from './utils/logger.js';

// Daemon HTTP client (talks to `qwen serve`)
export {
  DAEMON_APPROVAL_MODES,
  DAEMON_ERROR_KINDS,
  DAEMON_KNOWN_EVENT_TYPE_VALUES,
  PENDING_PROMPT_ADDED_EVENT,
  PENDING_PROMPT_STARTED_EVENT,
  PENDING_PROMPT_COMPLETED_EVENT,
  DaemonCapabilityMissingError,
  DaemonClient,
  DaemonHttpError,
  DaemonPendingPromptLimitError,
  DaemonSessionIdProtocolError,
  WorkspaceDaemonClient,
  DaemonSessionClient,
  asKnownDaemonEvent,
  createDaemonSessionViewState,
  isDaemonContentHash,
  isDaemonEventType,
  isKnownDaemonEvent,
  isWorkspaceScopedBudgetEvent,
  parseSseStream,
  reduceDaemonSessionEvent,
  reduceDaemonSessionEvents,
  requireWorkspaceCwd,
  SseFramingError,
  type CreateSessionRequest,
  type DaemonApprovalMode,
  type DaemonApprovalModeChangedData,
  type DaemonApprovalModeChangedEvent,
  type DaemonApprovalModeResult,
  type DaemonGithubSetupCompletedData,
  type DaemonGithubSetupCompletedEvent,
  type DaemonGithubSetupGitignoreResult,
  type DaemonGithubSetupRequest,
  type DaemonGithubSetupResult,
  type DaemonGithubSetupWorkflowResult,
  type DaemonInitWorkspaceResult,
  type DaemonMcpRestartResult,
  type DaemonReloadResponse,
  type DaemonChannelControlState,
  type DaemonChannelControlTransition,
  type DaemonChannelDelivery,
  type DaemonChannelNotifyRequest,
  type DaemonChannelNotifyResult,
  type DaemonChannelDeliveryErrorCode,
  type DaemonChannelDeliveryResultData,
  type DaemonChannelDeliveryResultEvent,
  type DaemonChannelReloadResult,
  type DaemonChannelSelection,
  type DaemonChannelSetResult,
  type DaemonChannelStartupAttemptFailure,
  type DaemonChannelStartupFailure,
  type DaemonChannelStopResult,
  type DaemonChannelWorkerStartErrorResponse,
  type DaemonChannelConfigFieldKind,
  type DaemonChannelConfigFieldDescriptor,
  type DaemonChannelConfigValueFieldDescriptor,
  type DaemonChannelConfigPlainValueFieldDescriptor,
  type DaemonChannelConfigEnumFieldDescriptor,
  type DaemonChannelConfigNumberFieldDescriptor,
  type DaemonChannelConfigObjectFieldDescriptor,
  type DaemonChannelConfigNestedFieldDescriptor,
  type DaemonChannelTypeDescriptor,
  type DaemonChannelTypeCatalog,
  type DaemonChannelRuntimeState,
  type DaemonChannelSecretState,
  type DaemonChannelInstanceSnapshot,
  type DaemonChannelsSnapshot,
  type DaemonChannelSecretUpdate,
  type DaemonRevisionRequest,
  type DaemonChannelUpsertRequest,
  type DaemonChannelStartupRequest,
  type DaemonChannelMutationResult,
  type DaemonChannelPairingRequest,
  type DaemonChannelPairingSubject,
  type DaemonChannelPairingRequestsSnapshot,
  type DaemonChannelPairingApprovalRequest,
  type DaemonChannelPairingApprovalResult,
  type DaemonChannelPairingApprovalsSnapshot,
  type DaemonChannelPairingRevocationRequest,
  type DaemonChannelPairingRevocationResult,
  type DaemonChannelManagementOptions,
  type DaemonSessionRecapResult,
  type DaemonShellCommandResult,
  type DaemonRuntimeMcpAddRequest,
  type DaemonRuntimeMcpAddResult,
  type DaemonRuntimeMcpRemoveResult,
  type DaemonMcpServerAddedData,
  type DaemonMcpServerAddedEvent,
  type DaemonMcpServerRemovedData,
  type DaemonMcpServerRemovedEvent,
  type DaemonMcpServerRestartedData,
  type DaemonMcpServerRestartedEvent,
  type DaemonMcpServerRestartRefusedData,
  type DaemonMcpServerRestartRefusedEvent,
  type DaemonSettingsReloadedData,
  type DaemonSettingsReloadedEvent,
  type DaemonSettingsChangedData,
  type DaemonSettingsChangedEvent,
  type DaemonToolToggleResult,
  type DaemonSkillBatchToggleError,
  type DaemonSkillBatchToggleErrorCode,
  type DaemonSkillBatchToggleItem,
  type DaemonSkillBatchToggleResult,
  type DaemonSkillToggleActivation,
  type DaemonSkillToggleMutation,
  type DaemonSkillToggleMutationSkill,
  type DaemonSkillToggleResult,
  type DaemonSkillScope,
  type DaemonSkillInstallSource,
  type DaemonSkillInstallRequest,
  type DaemonSkillMutationResult,
  type DaemonToolToggledData,
  type DaemonToolToggledEvent,
  type DaemonTrustChangeRequestedData,
  type DaemonTrustChangeRequestedEvent,
  type DaemonWorkspaceInitializedData,
  type DaemonWorkspaceInitializedEvent,
  type DaemonWorkspaceCapability,
  type DaemonWorkspaceUpdate,
  type DaemonWorkspaceGitStatus,
  type DaemonGitOperation,
  type DaemonWorkspaceGitDiff,
  type DaemonWorkspaceGitDiffFile,
  type DaemonWorkspaceGitDiffHunks,
  type DaemonDiffHunk,
  type DaemonGitLogEntry,
  type DaemonGitLog,
  type DaemonGitCommitFileStat,
  type DaemonGitCommitDetail,
  type DaemonWorkspaceRemovalActivity,
  type DaemonWorkspaceRemovalResult,
  type DaemonAvailableCommand,
  type DaemonCapabilities,
  type DaemonEnvCell,
  type DaemonEnvKind,
  type DaemonErrorKind,
  type DaemonClientEvictedData,
  type DaemonClientEvictedEvent,
  type DaemonHistoryTruncatedData,
  type DaemonHistoryTruncatedEvent,
  type DaemonPendingPromptAddedData,
  type DaemonPendingPromptAddedEvent,
  type DaemonPendingPromptStartedData,
  type DaemonPendingPromptStartedEvent,
  type DaemonPendingPromptCompletedData,
  type DaemonPendingPromptCompletedEvent,
  type DaemonPendingPromptEvent,
  type DaemonPendingPromptSummary,
  type DaemonPendingPromptsResult,
  type DaemonRemovePendingPromptResult,
  type DaemonRemoveMidTurnMessageResult,
  // Daemon-emitted resync
  // signal for SSE reconnects past the ring eviction boundary.
  type DaemonStateResyncRequiredData,
  type DaemonStateResyncRequiredEvent,
  type DaemonClientOptions,
  type DaemonContentHash,
  type DaemonControlEvent,
  type DaemonEvent,
  type DaemonEventEnvelope,
  type DaemonKnownEventType,
  // MCP guardrail push-event types.
  type DaemonMcpBudgetWarningData,
  type DaemonMcpBudgetWarningEvent,
  type DaemonMcpChildRefusedBatchData,
  type DaemonMcpChildRefusedBatchEvent,
  type DaemonMcpGuardrailEvent,
  type DaemonMcpRefusedServer,
  type DaemonMcpDiscoveryState,
  type DaemonMcpServerRuntimeStatus,
  type DaemonMcpTransport,
  type DaemonMode,
  type DaemonModelSwitchedData,
  type DaemonModelSwitchedEvent,
  type DaemonModelSwitchFailedData,
  type DaemonModelSwitchFailedEvent,
  type DaemonPermissionOption,
  type DaemonPermissionAlreadyResolvedData,
  type DaemonPermissionAlreadyResolvedEvent,
  type DaemonPermissionForbiddenData,
  type DaemonPermissionForbiddenEvent,
  type DaemonPermissionPartialVoteData,
  type DaemonPermissionPartialVoteEvent,
  type DaemonPermissionRequestData,
  type DaemonPermissionRequestEvent,
  type DaemonPermissionResolvedData,
  type DaemonPermissionResolvedEvent,
  type DaemonPendingInteraction,
  type DaemonPendingInteractionOption,
  type DaemonPendingPermissionInteraction,
  type DaemonPendingUserQuestion,
  type DaemonPendingUserQuestionInteraction,
  type DaemonProtocolVersions,
  type DaemonRestoredSession,
  type DaemonSession,
  type DaemonSessionClosedReason,
  type DaemonWorktreeInfo,
  type DaemonBranchInfo,
  type DaemonSessionClientOptions,
  type DaemonSessionContextStatus,
  type DaemonLspServerStatus,
  type DaemonSessionLspStatus,
  type DaemonSessionAgentTaskStatus,
  type DaemonSessionMonitorTaskStatus,
  type DaemonSessionProcessTaskLifecycleStatus,
  type DaemonSessionDiedData,
  type DaemonSessionDiedEvent,
  type DaemonSessionEvent,
  type DaemonSessionGroup,
  type DaemonSessionGroupCatalog,
  type DaemonSessionGroupColor,
  type DaemonSessionGroupHexColor,
  type DaemonSessionGroupPresetColor,
  type DaemonSessionGroupFilter,
  type DaemonSessionGroupInput,
  type DaemonSessionGroupUpdate,
  type DaemonSessionShellTaskStatus,
  type DaemonSessionTranscriptPage,
  type DaemonSessionTranscriptPageOptions,
  type DaemonSessionListPage,
  type DaemonSessionListPageOptions,
  type DaemonSessionListView,
  type DaemonSessionCatalogVersion,
  type DaemonSessionLiveState,
  type DaemonWorkspaceSessionLiveState,
  type DaemonSessionOrganizationResult,
  type DaemonSessionOrganizationUpdate,
  type DaemonSessionSubscribeOptions,
  type DaemonSessionState,
  type DaemonSessionSummary,
  type DaemonSessionSupportedCommandsStatus,
  type DaemonSessionTaskLifecycleStatus,
  type DaemonSessionTaskStatus,
  type DaemonSessionTasksStatus,
  type DaemonSkillLevel,
  type DaemonPreflightCell,
  type DaemonPreflightKind,
  type DaemonStatus,
  type DaemonChannelWorkerGroupSnapshot,
  type DaemonChannelWorkerSnapshot,
  type DaemonStatusCell,
  type DaemonLogHealth,
  type DaemonLogIssue,
  type DaemonLogMode,
  type DaemonStatusReport,
  type DaemonStatusReportDetail,
  type DaemonStatusReportIssue,
  type DaemonStatusReportLevel,
  type DaemonStatusReportSection,
  type DaemonStatusReportSession,
  type DaemonWorkspaceEnvStatus,
  type DaemonWorkspaceFile,
  type DaemonWorkspaceFileBytes,
  type DaemonWorkspaceFileEditRequest,
  type DaemonWorkspaceFileEditResult,
  type DaemonWorkspaceFileUploadRequest,
  type DaemonWorkspaceFileUploadResult,
  type DaemonWorkspaceFileWriteRequest,
  type DaemonWorkspaceFileWriteResult,
  type DaemonWorkspaceMemoryDreamOptions,
  type DaemonWorkspaceMemoryDreamResult,
  type DaemonWorkspaceMemoryDreamTask,
  type DaemonWorkspaceMemoryForgetMatch,
  type DaemonWorkspaceMemoryForgetOptions,
  type DaemonWorkspaceMemoryForgetResult,
  type DaemonWorkspaceMemoryForgetTask,
  type DaemonWorkspaceMemoryRememberContextMode,
  type DaemonWorkspaceMemoryRememberOptions,
  type DaemonWorkspaceMemoryRememberResult,
  type DaemonWorkspaceMemoryRememberTask,
  type DaemonWorkspaceMemoryRememberTaskStatus,
  type DaemonWorkspaceMemoryTaskStatus,
  type DaemonWorkspaceMemoryTopic,
  type DaemonWorkspacePreflightStatus,
  type DaemonSessionUpdateData,
  type DaemonSessionUpdateEvent,
  type DaemonSessionRecordingDegradedData,
  type DaemonSessionRecordingDegradedEvent,
  type DaemonSessionViewState,
  type DaemonSlowClientWarningData,
  type DaemonSlowClientWarningEvent,
  type DaemonStreamErrorData,
  type DaemonStreamErrorEvent,
  type DaemonStreamLifecycleEvent,
  // Daemon assist push (server-side ghost-text suggestion)
  type DaemonAssistEvent,
  type DaemonFollowupSuggestionData,
  type DaemonFollowupSuggestionEvent,
  type DaemonWorkspaceMcpServerStatus,
  type DaemonWorkspaceMcpStatus,
  type DaemonWorkspaceMcpInitializeResult,
  type DaemonWorkspaceAcpStatusResult,
  type DaemonWorkspaceAcpPreheatResult,
  type DaemonWorkspaceProviderCurrent,
  type DaemonWorkspaceProviderModel,
  type DaemonWorkspaceProviderStatus,
  type DaemonWorkspaceProvidersStatus,
  type DaemonWorkspaceSkillStatus,
  type DaemonWorkspaceSkillsStatus,
  type DaemonWorkspaceTrustChangeRequest,
  type DaemonWorkspaceTrustChangeResult,
  type DaemonWorkspaceTrustDesiredState,
  type DaemonWorkspaceTrustLevel,
  type DaemonWorkspaceTrustSource,
  type DaemonWorkspaceTrustState,
  type DaemonWorkspaceTrustStatus,
  type DaemonWorkspaceTrustStatusResponse,
  type DaemonWorkspaceTrustStatusV2,
  type DaemonWorkspaceTrustReconciliationState,
  type DaemonVoiceAudioInput,
  type DaemonVoiceMode,
  type DaemonVoiceModelDescriptor,
  type DaemonVoiceTransport,
  type DaemonWorkspaceVoiceStatus,
  type DaemonWorkspaceVoiceTranscribeOptions,
  type DaemonWorkspaceVoiceTranscriptionResult,
  type DaemonWorkspaceVoiceUpdate,
  type DaemonLiveBlocker,
  type DaemonLiveHostInstallState,
  type DaemonLiveHostInstallStatus,
  type DaemonLiveMuteUpdate,
  type DaemonLiveRequirementState,
  type DaemonLiveSetupApiKeyMutation,
  type DaemonLiveSetupStatus,
  type DaemonLiveSetupUpdate,
  type DaemonLiveState,
  type DaemonLiveStatus,
  type DaemonSseConnectReason,
  type HeartbeatResult,
  type KnownDaemonEvent,
  type MCPServerConfigShape,
  type PermissionOutcome,
  type PermissionOutcomeCancelled,
  type PermissionOutcomeSelected,
  type PermissionResponse,
  type PromptContentBlock,
  // BRSCv: drop the historical `Daemon`-prefixed aliases for
  // consistency with the rest of the daemon-type exports
  // (CreateSessionRequest / DaemonSession / PromptResult / etc. are
  // all exported un-prefixed). The prefix on these two was a
  // transitional artifact from when the daemon types lived alongside
  // older non-daemon types of the same name; they don't anymore.
  // The SDK is Stage-1-experimental with no shipping consumers, so
  // breaking the alias is cheaper than carrying inconsistent naming
  // forward into Stage 2.
  type PromptRequest,
  type PromptResult,
  type PromptTextContent,
  type RestoreSessionRequest,
  type SetModelResult,
  type SetSessionLanguageResult,
  type SessionMetadataResult,
  type SubscribeOptions,
} from './daemon/index.js';

// Auth
// surface. These were re-exported from `./daemon/index.js` but the
// public SDK entry (this file) never re-exported them, so an
// `import { DaemonAuthFlow } from '@qwen-code/sdk'` resolved to
// undefined. The PR description lists `reduceDaemonAuthEvent` as
// SDK surface and `client.auth.start()` works only because
// `DaemonClient` (already exported above) constructs `DaemonAuthFlow`
// internally; every other API path was unreachable.
export {
  DaemonAuthFlow,
  DEVICE_FLOW_EXPIRY_GRACE_MS,
  createDaemonAuthState,
  reduceDaemonAuthEvent,
  reduceDaemonAuthEvents,
  type AwaitCompletionOptions,
  type DaemonAuthDeviceFlowAuthorizedData,
  type DaemonAuthDeviceFlowAuthorizedEvent,
  type DaemonAuthDeviceFlowCancelledData,
  type DaemonAuthDeviceFlowCancelledEvent,
  type DaemonAuthDeviceFlowErrorKind,
  type DaemonAuthDeviceFlowFailedData,
  type DaemonAuthDeviceFlowFailedEvent,
  type DaemonAuthDeviceFlowProviderId,
  type DaemonAuthDeviceFlowStartedData,
  type DaemonAuthDeviceFlowStartedEvent,
  type DaemonAuthDeviceFlowStatus,
  type DaemonAuthDeviceFlowThrottledData,
  type DaemonAuthDeviceFlowThrottledEvent,
  type DaemonAuthEvent,
  type DaemonAuthFlowHandle,
  type DaemonAuthProviderId,
  type DaemonAuthState,
  type DaemonAuthStatusSnapshot,
  type DaemonDeviceFlowReducerState,
  type DaemonDeviceFlowStartResult,
  type DaemonDeviceFlowState,
} from './daemon/index.js';

// SDK MCP Server exports
export { tool } from './daemon-mcp/tool.js';
export { createSdkMcpServer } from './daemon-mcp/createSdkMcpServer.js';
export { createServeBridgeMcpServer } from './daemon-mcp/serve-bridge/index.js';

export type { SdkMcpToolDefinition } from './daemon-mcp/tool.js';

export type {
  CreateSdkMcpServerOptions,
  McpSdkServerConfigWithInstance,
} from './daemon-mcp/createSdkMcpServer.js';

export type { ServeBridgeMcpServerOptions } from './daemon-mcp/serve-bridge/index.js';

export type { QueryOptions } from './query/createQuery.js';
export type {
  EffortOverride,
  EffortStatus,
  EffortTier,
} from './types/types.js';
export type { LogLevel, LoggerConfig, ScopedLogger } from './utils/logger.js';

export type {
  ContentBlock,
  TextBlock,
  ThinkingBlock,
  ToolUseBlock,
  ToolResultBlock,
  SDKUserMessage,
  SDKAssistantMessage,
  SDKSystemMessage,
  SDKResultMessage,
  SDKPartialAssistantMessage,
  SDKMessage,
  SDKMcpServerConfig,
  ControlMessage,
  CLIControlRequest,
  CLIControlResponse,
  ControlCancelRequest,
  SubagentConfig,
  SubagentLevel,
  RunConfig,
} from './types/protocol.js';

export {
  isSDKUserMessage,
  isSDKAssistantMessage,
  isSDKSystemMessage,
  isSDKResultMessage,
  isSDKPartialAssistantMessage,
  isControlRequest,
  isControlResponse,
  isControlCancel,
} from './types/protocol.js';

export type {
  PermissionMode,
  CanUseTool,
  PermissionResult,
  QuerySystemPrompt,
  QuerySystemPromptPreset,
  CLIMcpServerConfig,
  McpServerConfig,
  McpOAuthConfig,
  McpAuthProviderType,
} from './types/types.js';

export { isSdkMcpServerConfig } from './types/types.js';
