/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Ed25519 signature verification for standalone update integrity.
 *
 * The release CI signs SHA256SUMS with an Ed25519 private key, producing
 * SHA256SUMS.sig (base64-encoded raw 64-byte signature). This module
 * verifies that signature using the embedded public key.
 *
 * Key generation (one-time):
 *   openssl genpkey -algorithm Ed25519 -out release-signing-key.pem
 *   openssl pkey -in release-signing-key.pem -pubout -outform DER | base64
 */

import { createPublicKey, verify } from 'node:crypto';

// Ed25519 public key in DER/SPKI format, base64-encoded.
// Replace this with the production key generated by the release team.
// The corresponding private key must be stored in CI secrets only.
const RELEASE_PUBLIC_KEY_DER_B64 =
  'MCowBQYDK2VwAyEAr9WRFLDauibZQKCe1oKfuFZn6zRMaEkD5+KVqN6mKM4=';

/**
 * Verifies an Ed25519 signature over the SHA256SUMS content.
 * @param sha256sumsContent - The raw text of SHA256SUMS
 * @param signatureBase64 - Base64-encoded 64-byte Ed25519 signature
 * @throws if signature is invalid or verification fails
 */
export function verifySignature(
  sha256sumsContent: string,
  signatureBase64: string,
): void {
  const key = createPublicKey({
    key: Buffer.from(RELEASE_PUBLIC_KEY_DER_B64, 'base64'),
    format: 'der',
    type: 'spki',
  });

  const signature = Buffer.from(signatureBase64, 'base64');
  if (signature.length !== 64) {
    throw new Error(
      `Invalid signature length: expected 64 bytes, got ${signature.length}`,
    );
  }

  const valid = verify(null, Buffer.from(sha256sumsContent), key, signature);
  if (!valid) {
    throw new Error(
      'SHA256SUMS signature verification failed — possible tampering detected',
    );
  }
}
